########## This file is automatically generated. Any changes to this file will be lost. ##########
########## If you have your own constraints tcl file, please add it to the project ##########
########## by using the "Set custom config file" constraint in the HLS Constraints dialog. ##########
source $env(SHLS_ROOT_DIR)/examples/shls.tcl
set_project PolarFireSoC MPFS095T-FCSG325E hw_only
set_synthesis_top_module canny_top
set_parameter CLOCK_PERIOD 10
