// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fir_hw_fir_hw,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.764300,HLS_SYN_LAT=324,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=495,HLS_SYN_LUT=867,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module fir_hw (
        ap_clk,
        ap_rst_n,
        input_l,
        input_l_ap_vld,
        input_l_ap_ack,
        input_r,
        input_r_ap_vld,
        input_r_ap_ack,
        res_TDATA,
        res_TVALID,
        res_TREADY,
        res_TKEEP,
        res_TSTRB,
        res_TLAST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 12;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [23:0] input_l;
input   input_l_ap_vld;
output   input_l_ap_ack;
input  [23:0] input_r;
input   input_r_ap_vld;
output   input_r_ap_ack;
output  [31:0] res_TDATA;
output   res_TVALID;
input   res_TREADY;
output  [3:0] res_TKEEP;
output  [3:0] res_TSTRB;
output  [0:0] res_TLAST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

reg input_l_ap_ack;
reg input_r_ap_ack;

 reg    ap_rst_n_inv;
wire   [15:0] tlast_dnum;
wire   [2:0] smpl_rd_num;
wire   [8:0] tap_num_m1;
wire   [31:0] coeff_hw_q0;
reg   [8:0] write_idx;
reg   [8:0] buffer_left_address0;
reg    buffer_left_ce0;
wire   [23:0] buffer_left_q0;
reg   [8:0] buffer_right_address0;
reg    buffer_right_ce0;
wire   [23:0] buffer_right_q0;
reg   [2:0] dec_cnt;
reg   [15:0] cnt;
reg    input_l_blk_n;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    input_r_blk_n;
reg    res_TDATA_blk_n;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg   [0:0] icmp_ln26_reg_360;
reg   [8:0] tap_num_m1_read_reg_335;
wire   [2:0] add_ln25_fu_238_p2;
wire   [0:0] icmp_ln26_fu_244_p2;
wire   [0:0] out_data_last_fu_260_p2;
reg   [0:0] out_data_last_reg_364;
wire   [0:0] out_data_last_1_fu_280_p2;
reg   [0:0] out_data_last_1_reg_369;
wire   [9:0] add_ln32_fu_303_p2;
reg   [9:0] add_ln32_reg_374;
wire    ap_CS_fsm_state2;
wire    grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_start;
wire    grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_done;
wire    grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_idle;
wire    grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_ready;
wire   [8:0] grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_coeff_hw_address0;
wire    grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_coeff_hw_ce0;
wire   [31:0] grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_out_data_data_out;
wire    grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_out_data_data_out_ap_vld;
wire   [31:0] grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_out_data_data_1_out;
wire    grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_out_data_data_1_out_ap_vld;
wire   [8:0] grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_left_address0;
wire    grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_left_ce0;
wire   [8:0] grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_right_address0;
wire    grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_right_ce0;
reg   [2:0] ap_phi_mux_dec_cnt_new_0_phi_fu_203_p4;
reg   [2:0] dec_cnt_new_0_reg_200;
reg    ap_block_state1;
wire    regslice_both_res_V_data_V_U_apdone_blk;
reg    ap_block_state6;
reg    grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_start_reg;
wire    ap_CS_fsm_state3;
wire   [63:0] zext_ln22_fu_228_p1;
wire   [8:0] add_ln65_fu_318_p2;
wire   [15:0] select_ln60_fu_286_p3;
reg    buffer_left_we0_local;
reg    buffer_left_ce0_local;
reg    buffer_right_we0_local;
reg    buffer_right_ce0_local;
wire   [15:0] add_ln43_fu_254_p2;
wire   [15:0] add_ln54_fu_266_p2;
wire   [15:0] select_ln54_fu_272_p3;
wire   [9:0] zext_ln32_fu_300_p1;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg   [31:0] res_TDATA_int_regslice;
reg    res_TVALID_int_regslice;
wire    res_TREADY_int_regslice;
wire    regslice_both_res_V_data_V_U_vld_out;
wire    regslice_both_res_V_keep_V_U_apdone_blk;
wire    regslice_both_res_V_keep_V_U_ack_in_dummy;
wire    regslice_both_res_V_keep_V_U_vld_out;
wire    regslice_both_res_V_strb_V_U_apdone_blk;
wire    regslice_both_res_V_strb_V_U_ack_in_dummy;
wire    regslice_both_res_V_strb_V_U_vld_out;
wire    regslice_both_res_V_last_V_U_apdone_blk;
reg   [0:0] res_TLAST_int_regslice;
wire    regslice_both_res_V_last_V_U_ack_in_dummy;
wire    regslice_both_res_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 write_idx = 9'd0;
#0 dec_cnt = 3'd0;
#0 cnt = 16'd0;
#0 ap_CS_fsm = 6'd1;
#0 grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_start_reg = 1'b0;
end

fir_hw_buffer_left_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
buffer_left_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buffer_left_address0),
    .ce0(buffer_left_ce0),
    .we0(buffer_left_we0_local),
    .d0(input_l),
    .q0(buffer_left_q0)
);

fir_hw_buffer_left_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
buffer_right_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buffer_right_address0),
    .ce0(buffer_right_ce0),
    .we0(buffer_right_we0_local),
    .d0(input_r),
    .q0(buffer_right_q0)
);

fir_hw_fir_hw_Pipeline_VITIS_LOOP_32_1 grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_start),
    .ap_done(grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_done),
    .ap_idle(grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_idle),
    .ap_ready(grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_ready),
    .add_ln32(add_ln32_reg_374),
    .write_idx_load(write_idx),
    .coeff_hw_address0(grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_coeff_hw_address0),
    .coeff_hw_ce0(grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_coeff_hw_ce0),
    .coeff_hw_q0(coeff_hw_q0),
    .out_data_data_out(grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_out_data_data_out),
    .out_data_data_out_ap_vld(grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_out_data_data_out_ap_vld),
    .out_data_data_1_out(grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_out_data_data_1_out),
    .out_data_data_1_out_ap_vld(grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_out_data_data_1_out_ap_vld),
    .buffer_left_address0(grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_left_address0),
    .buffer_left_ce0(grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_left_ce0),
    .buffer_left_q0(buffer_left_q0),
    .buffer_right_address0(grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_right_address0),
    .buffer_right_ce0(grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_right_ce0),
    .buffer_right_q0(buffer_right_q0)
);

fir_hw_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .tlast_dnum(tlast_dnum),
    .smpl_rd_num(smpl_rd_num),
    .tap_num_m1(tap_num_m1),
    .coeff_hw_address0(grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_coeff_hw_address0),
    .coeff_hw_ce0(grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_coeff_hw_ce0),
    .coeff_hw_q0(coeff_hw_q0)
);

fir_hw_regslice_both #(
    .DataWidth( 32 ))
regslice_both_res_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(res_TDATA_int_regslice),
    .vld_in(res_TVALID_int_regslice),
    .ack_in(res_TREADY_int_regslice),
    .data_out(res_TDATA),
    .vld_out(regslice_both_res_V_data_V_U_vld_out),
    .ack_out(res_TREADY),
    .apdone_blk(regslice_both_res_V_data_V_U_apdone_blk)
);

fir_hw_regslice_both #(
    .DataWidth( 4 ))
regslice_both_res_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(res_TVALID_int_regslice),
    .ack_in(regslice_both_res_V_keep_V_U_ack_in_dummy),
    .data_out(res_TKEEP),
    .vld_out(regslice_both_res_V_keep_V_U_vld_out),
    .ack_out(res_TREADY),
    .apdone_blk(regslice_both_res_V_keep_V_U_apdone_blk)
);

fir_hw_regslice_both #(
    .DataWidth( 4 ))
regslice_both_res_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(res_TVALID_int_regslice),
    .ack_in(regslice_both_res_V_strb_V_U_ack_in_dummy),
    .data_out(res_TSTRB),
    .vld_out(regslice_both_res_V_strb_V_U_vld_out),
    .ack_out(res_TREADY),
    .apdone_blk(regslice_both_res_V_strb_V_U_apdone_blk)
);

fir_hw_regslice_both #(
    .DataWidth( 1 ))
regslice_both_res_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(res_TLAST_int_regslice),
    .vld_in(res_TVALID_int_regslice),
    .ack_in(regslice_both_res_V_last_V_U_ack_in_dummy),
    .data_out(res_TLAST),
    .vld_out(regslice_both_res_V_last_V_U_vld_out),
    .ack_out(res_TREADY),
    .apdone_blk(regslice_both_res_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_start_reg <= 1'b1;
        end else if ((grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_ready == 1'b1)) begin
            grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln26_reg_360 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6))) begin
        dec_cnt_new_0_reg_200 <= 3'd0;
    end else if (((icmp_ln26_fu_244_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        dec_cnt_new_0_reg_200 <= add_ln25_fu_238_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln32_reg_374 <= add_ln32_fu_303_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln26_fu_244_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        cnt <= select_ln60_fu_286_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6))) begin
        dec_cnt <= ap_phi_mux_dec_cnt_new_0_phi_fu_203_p4;
        write_idx <= add_ln65_fu_318_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln26_reg_360 <= icmp_ln26_fu_244_p2;
        out_data_last_1_reg_369 <= out_data_last_1_fu_280_p2;
        out_data_last_reg_364 <= out_data_last_fu_260_p2;
        tap_num_m1_read_reg_335 <= tap_num_m1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((res_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((res_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state6)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln26_reg_360 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_phi_mux_dec_cnt_new_0_phi_fu_203_p4 = 3'd0;
    end else begin
        ap_phi_mux_dec_cnt_new_0_phi_fu_203_p4 = dec_cnt_new_0_reg_200;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer_left_address0 = grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_left_address0;
    end else begin
        buffer_left_address0 = zext_ln22_fu_228_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer_left_ce0 = grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_left_ce0;
    end else begin
        buffer_left_ce0 = buffer_left_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        buffer_left_ce0_local = 1'b1;
    end else begin
        buffer_left_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        buffer_left_we0_local = 1'b1;
    end else begin
        buffer_left_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer_right_address0 = grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_right_address0;
    end else begin
        buffer_right_address0 = zext_ln22_fu_228_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer_right_ce0 = grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_right_ce0;
    end else begin
        buffer_right_ce0 = buffer_right_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        buffer_right_ce0_local = 1'b1;
    end else begin
        buffer_right_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        buffer_right_we0_local = 1'b1;
    end else begin
        buffer_right_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        input_l_ap_ack = 1'b1;
    end else begin
        input_l_ap_ack = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        input_l_blk_n = input_l_ap_vld;
    end else begin
        input_l_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        input_r_ap_ack = 1'b1;
    end else begin
        input_r_ap_ack = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        input_r_blk_n = input_r_ap_vld;
    end else begin
        input_r_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln26_reg_360 == 1'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        res_TDATA_blk_n = res_TREADY_int_regslice;
    end else begin
        res_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((res_TREADY_int_regslice == 1'b1)) begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            res_TDATA_int_regslice = grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_out_data_data_1_out;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            res_TDATA_int_regslice = grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_out_data_data_out;
        end else begin
            res_TDATA_int_regslice = 'bx;
        end
    end else begin
        res_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((res_TREADY_int_regslice == 1'b1)) begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            res_TLAST_int_regslice = out_data_last_1_reg_369;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            res_TLAST_int_regslice = out_data_last_reg_364;
        end else begin
            res_TLAST_int_regslice = 'bx;
        end
    end else begin
        res_TLAST_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((((res_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((res_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4)))) begin
        res_TVALID_int_regslice = 1'b1;
    end else begin
        res_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln26_fu_244_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else if (((icmp_ln26_fu_244_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((res_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((res_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln25_fu_238_p2 = (dec_cnt + 3'd1);

assign add_ln32_fu_303_p2 = (zext_ln32_fu_300_p1 + 10'd1);

assign add_ln43_fu_254_p2 = (cnt + 16'd1);

assign add_ln54_fu_266_p2 = (cnt + 16'd2);

assign add_ln65_fu_318_p2 = (write_idx + 9'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state1 = ((input_r_ap_vld == 1'b0) | (input_l_ap_vld == 1'b0));
end

always @ (*) begin
    ap_block_state6 = ((regslice_both_res_V_data_V_U_apdone_blk == 1'b1) | ((icmp_ln26_reg_360 == 1'd0) & (res_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_start = grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_start_reg;

assign icmp_ln26_fu_244_p2 = ((add_ln25_fu_238_p2 < smpl_rd_num) ? 1'b1 : 1'b0);

assign out_data_last_1_fu_280_p2 = ((select_ln54_fu_272_p3 == tlast_dnum) ? 1'b1 : 1'b0);

assign out_data_last_fu_260_p2 = ((add_ln43_fu_254_p2 == tlast_dnum) ? 1'b1 : 1'b0);

assign res_TVALID = regslice_both_res_V_data_V_U_vld_out;

assign select_ln54_fu_272_p3 = ((out_data_last_fu_260_p2[0:0] == 1'b1) ? 16'd1 : add_ln54_fu_266_p2);

assign select_ln60_fu_286_p3 = ((out_data_last_1_fu_280_p2[0:0] == 1'b1) ? 16'd0 : select_ln54_fu_272_p3);

assign zext_ln22_fu_228_p1 = write_idx;

assign zext_ln32_fu_300_p1 = tap_num_m1_read_reg_335;


reg find_kernel_block = 0;
// synthesis translate_off
`include "fir_hw_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //fir_hw

