-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bypass_hw is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    input_l : IN STD_LOGIC_VECTOR (23 downto 0);
    input_l_ap_vld : IN STD_LOGIC;
    input_l_ap_ack : OUT STD_LOGIC;
    input_r : IN STD_LOGIC_VECTOR (23 downto 0);
    input_r_ap_vld : IN STD_LOGIC;
    input_r_ap_ack : OUT STD_LOGIC;
    res_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    res_TVALID : OUT STD_LOGIC;
    res_TREADY : IN STD_LOGIC;
    res_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    res_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    res_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of bypass_hw is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "bypass_hw_bypass_hw,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.420000,HLS_SYN_LAT=2,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=96,HLS_SYN_LUT=275,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000010";

    signal ap_rst_n_inv : STD_LOGIC;
    signal tlast_dnum : STD_LOGIC_VECTOR (15 downto 0);
    signal cnt : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_l_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal input_r_blk_n : STD_LOGIC;
    signal res_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal out_data_data_fu_118_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_data_last_fu_127_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal input_r_read_reg_186 : STD_LOGIC_VECTOR (23 downto 0);
    signal out_data_last_1_fu_148_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_data_last_1_reg_191 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_data_data_1_fu_168_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln39_fu_154_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal add_ln22_fu_112_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln33_fu_134_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln33_fu_140_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal regslice_both_res_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state3 : BOOLEAN;
    signal res_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal res_TVALID_int_regslice : STD_LOGIC;
    signal res_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_res_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_res_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_res_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_res_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_res_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_res_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_res_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_res_V_last_V_U_apdone_blk : STD_LOGIC;
    signal res_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_res_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_res_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component bypass_hw_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        tlast_dnum : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component bypass_hw_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    control_s_axi_U : component bypass_hw_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        tlast_dnum => tlast_dnum);

    regslice_both_res_V_data_V_U : component bypass_hw_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => res_TDATA_int_regslice,
        vld_in => res_TVALID_int_regslice,
        ack_in => res_TREADY_int_regslice,
        data_out => res_TDATA,
        vld_out => regslice_both_res_V_data_V_U_vld_out,
        ack_out => res_TREADY,
        apdone_blk => regslice_both_res_V_data_V_U_apdone_blk);

    regslice_both_res_V_keep_V_U : component bypass_hw_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => res_TVALID_int_regslice,
        ack_in => regslice_both_res_V_keep_V_U_ack_in_dummy,
        data_out => res_TKEEP,
        vld_out => regslice_both_res_V_keep_V_U_vld_out,
        ack_out => res_TREADY,
        apdone_blk => regslice_both_res_V_keep_V_U_apdone_blk);

    regslice_both_res_V_strb_V_U : component bypass_hw_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => res_TVALID_int_regslice,
        ack_in => regslice_both_res_V_strb_V_U_ack_in_dummy,
        data_out => res_TSTRB,
        vld_out => regslice_both_res_V_strb_V_U_vld_out,
        ack_out => res_TREADY,
        apdone_blk => regslice_both_res_V_strb_V_U_apdone_blk);

    regslice_both_res_V_last_V_U : component bypass_hw_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => res_TLAST_int_regslice,
        vld_in => res_TVALID_int_regslice,
        ack_in => regslice_both_res_V_last_V_U_ack_in_dummy,
        data_out => res_TLAST,
        vld_out => regslice_both_res_V_last_V_U_vld_out,
        ack_out => res_TREADY,
        apdone_blk => regslice_both_res_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                cnt <= select_ln39_fu_154_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                input_r_read_reg_186 <= input_r;
                out_data_last_1_reg_191 <= out_data_last_1_fu_148_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_block_state1, ap_block_state3, res_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (res_TREADY_int_regslice = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln22_fu_112_p2 <= std_logic_vector(unsigned(cnt) + unsigned(ap_const_lv16_1));
    add_ln33_fu_134_p2 <= std_logic_vector(unsigned(cnt) + unsigned(ap_const_lv16_2));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(res_TREADY_int_regslice)
    begin
        if ((res_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3)
    begin
        if ((ap_const_boolean_1 = ap_block_state3)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(input_l_ap_vld, input_r_ap_vld, res_TREADY_int_regslice)
    begin
                ap_block_state1 <= ((res_TREADY_int_regslice = ap_const_logic_0) or (input_r_ap_vld = ap_const_logic_0) or (input_l_ap_vld = ap_const_logic_0));
    end process;


    ap_block_state3_assign_proc : process(regslice_both_res_V_data_V_U_apdone_blk, res_TREADY_int_regslice)
    begin
                ap_block_state3 <= ((res_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_res_V_data_V_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    input_l_ap_ack_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            input_l_ap_ack <= ap_const_logic_1;
        else 
            input_l_ap_ack <= ap_const_logic_0;
        end if; 
    end process;


    input_l_blk_n_assign_proc : process(input_l_ap_vld, ap_CS_fsm_state1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            input_l_blk_n <= input_l_ap_vld;
        else 
            input_l_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    input_r_ap_ack_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            input_r_ap_ack <= ap_const_logic_1;
        else 
            input_r_ap_ack <= ap_const_logic_0;
        end if; 
    end process;


    input_r_blk_n_assign_proc : process(input_r_ap_vld, ap_CS_fsm_state1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            input_r_blk_n <= input_r_ap_vld;
        else 
            input_r_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_data_data_1_fu_168_p3 <= (input_r_read_reg_186 & ap_const_lv8_0);
    out_data_data_fu_118_p3 <= (input_l & ap_const_lv8_0);
    out_data_last_1_fu_148_p2 <= "1" when (select_ln33_fu_140_p3 = tlast_dnum) else "0";
    out_data_last_fu_127_p2 <= "1" when (add_ln22_fu_112_p2 = tlast_dnum) else "0";

    res_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, res_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            res_TDATA_blk_n <= res_TREADY_int_regslice;
        else 
            res_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    res_TDATA_int_regslice_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, out_data_data_fu_118_p3, out_data_data_1_fu_168_p3, ap_block_state1, res_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (res_TREADY_int_regslice = ap_const_logic_1))) then 
            res_TDATA_int_regslice <= out_data_data_1_fu_168_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            res_TDATA_int_regslice <= out_data_data_fu_118_p3;
        else 
            res_TDATA_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    res_TLAST_int_regslice_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, out_data_last_fu_127_p2, out_data_last_1_reg_191, ap_block_state1, res_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (res_TREADY_int_regslice = ap_const_logic_1))) then 
            res_TLAST_int_regslice <= out_data_last_1_reg_191;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            res_TLAST_int_regslice <= out_data_last_fu_127_p2;
        else 
            res_TLAST_int_regslice <= "X";
        end if; 
    end process;

    res_TVALID <= regslice_both_res_V_data_V_U_vld_out;

    res_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_block_state1, res_TREADY_int_regslice)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state2) and (res_TREADY_int_regslice = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1)))) then 
            res_TVALID_int_regslice <= ap_const_logic_1;
        else 
            res_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    select_ln33_fu_140_p3 <= 
        ap_const_lv16_1 when (out_data_last_fu_127_p2(0) = '1') else 
        add_ln33_fu_134_p2;
    select_ln39_fu_154_p3 <= 
        ap_const_lv16_0 when (out_data_last_1_fu_148_p2(0) = '1') else 
        select_ln33_fu_140_p3;
end behav;
