# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pinout.xdc

# Block Designs: bd/cpu_system/cpu_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_system || ORIG_REF_NAME==cpu_system} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_zynq_ultra_ps_e_0_0/cpu_system_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_system_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==cpu_system_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_proc_sys_reset_0_0/cpu_system_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_system_proc_sys_reset_0_0 || ORIG_REF_NAME==cpu_system_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_smartconnect_0_0/cpu_system_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_system_smartconnect_0_0 || ORIG_REF_NAME==cpu_system_smartconnect_0_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_axi_gpio_0_0/cpu_system_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_system_axi_gpio_0_0 || ORIG_REF_NAME==cpu_system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_system_ila_0_0/cpu_system_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_system_system_ila_0_0 || ORIG_REF_NAME==cpu_system_system_ila_0_0} -quiet] -quiet

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/cpu_system_ooc.xdc
