# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.srcs/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/cpu_system_system_ila_0_0.xci
# IP: The module: 'cpu_system_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/bd_38aa.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa || ORIG_REF_NAME==bd_38aa} -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_0/bd_38aa_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa_ila_lib_0 || ORIG_REF_NAME==bd_38aa_ila_lib_0} -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_1/bd_38aa_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa_g_inst_0 || ORIG_REF_NAME==bd_38aa_g_inst_0} -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_2/bd_38aa_slot_0_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa_slot_0_aw_0 || ORIG_REF_NAME==bd_38aa_slot_0_aw_0} -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_3/bd_38aa_slot_0_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa_slot_0_w_0 || ORIG_REF_NAME==bd_38aa_slot_0_w_0} -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_4/bd_38aa_slot_0_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa_slot_0_b_0 || ORIG_REF_NAME==bd_38aa_slot_0_b_0} -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_5/bd_38aa_slot_0_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa_slot_0_ar_0 || ORIG_REF_NAME==bd_38aa_slot_0_ar_0} -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_6/bd_38aa_slot_0_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa_slot_0_r_0 || ORIG_REF_NAME==bd_38aa_slot_0_r_0} -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_7/bd_38aa_slot_1_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa_slot_1_aw_0 || ORIG_REF_NAME==bd_38aa_slot_1_aw_0} -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_8/bd_38aa_slot_1_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa_slot_1_w_0 || ORIG_REF_NAME==bd_38aa_slot_1_w_0} -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_9/bd_38aa_slot_1_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa_slot_1_b_0 || ORIG_REF_NAME==bd_38aa_slot_1_b_0} -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_10/bd_38aa_slot_1_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa_slot_1_ar_0 || ORIG_REF_NAME==bd_38aa_slot_1_ar_0} -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_11/bd_38aa_slot_1_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa_slot_1_r_0 || ORIG_REF_NAME==bd_38aa_slot_1_r_0} -quiet] -quiet

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_38aa_ila_lib_0 || ORIG_REF_NAME==bd_38aa_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_38aa_ila_lib_0 || ORIG_REF_NAME==bd_38aa_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_0/bd_38aa_ila_lib_0_ooc.xdc

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/bd_38aa_ooc.xdc

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/cpu_system_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_system_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.srcs/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/cpu_system_system_ila_0_0.xci
# IP: The module: 'cpu_system_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/bd_38aa.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa || ORIG_REF_NAME==bd_38aa} -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_0/bd_38aa_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa_ila_lib_0 || ORIG_REF_NAME==bd_38aa_ila_lib_0} -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_1/bd_38aa_g_inst_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa_g_inst_0 || ORIG_REF_NAME==bd_38aa_g_inst_0} -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_2/bd_38aa_slot_0_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa_slot_0_aw_0 || ORIG_REF_NAME==bd_38aa_slot_0_aw_0} -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_3/bd_38aa_slot_0_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa_slot_0_w_0 || ORIG_REF_NAME==bd_38aa_slot_0_w_0} -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_4/bd_38aa_slot_0_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa_slot_0_b_0 || ORIG_REF_NAME==bd_38aa_slot_0_b_0} -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_5/bd_38aa_slot_0_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa_slot_0_ar_0 || ORIG_REF_NAME==bd_38aa_slot_0_ar_0} -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_6/bd_38aa_slot_0_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa_slot_0_r_0 || ORIG_REF_NAME==bd_38aa_slot_0_r_0} -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_7/bd_38aa_slot_1_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa_slot_1_aw_0 || ORIG_REF_NAME==bd_38aa_slot_1_aw_0} -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_8/bd_38aa_slot_1_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa_slot_1_w_0 || ORIG_REF_NAME==bd_38aa_slot_1_w_0} -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_9/bd_38aa_slot_1_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa_slot_1_b_0 || ORIG_REF_NAME==bd_38aa_slot_1_b_0} -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_10/bd_38aa_slot_1_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa_slot_1_ar_0 || ORIG_REF_NAME==bd_38aa_slot_1_ar_0} -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_11/bd_38aa_slot_1_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_38aa_slot_1_r_0 || ORIG_REF_NAME==bd_38aa_slot_1_r_0} -quiet] -quiet

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_38aa_ila_lib_0 || ORIG_REF_NAME==bd_38aa_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_38aa_ila_lib_0 || ORIG_REF_NAME==bd_38aa_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/ip/ip_0/bd_38aa_ila_lib_0_ooc.xdc

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/bd_0/bd_38aa_ooc.xdc

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_system_ila_0_0/cpu_system_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_system_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
