// This file was autogenerated by SmartHLS on Nov 24 2025, 05:15:47

#pragma GCC diagnostic ignored "-Wpointer-arith"
#include "fir_hls_accelerator_driver.h"
#include <string.h>
#include <stdio.h>
#include <stdint.h>
#include <unistd.h>

void fir_hw_write_tlast_dnum(uint16_t val,  uint32_t base_addr) {

    *(volatile uint16_t *)(base_addr + 0x0) = (volatile uint16_t) val;
}

uint16_t fir_hw_read_tlast_dnum(uint32_t base_addr) {

    return *(volatile uint16_t *)(base_addr + 0x0);
}

void fir_hw_write_smpl_rd_num(uint8_t val,  uint32_t base_addr) {

    *(volatile uint8_t *)(base_addr + 0x4) = (volatile uint8_t) val;
}

uint8_t fir_hw_read_smpl_rd_num(uint32_t base_addr) {

    return *(volatile uint8_t *)(base_addr + 0x4);
}

void fir_hw_write_tap_num_m1(uint16_t val,  uint32_t base_addr) {

    *(volatile uint16_t *)(base_addr + 0x8) = (volatile uint16_t) val;
}

uint16_t fir_hw_read_tap_num_m1(uint32_t base_addr) {

    return *(volatile uint16_t *)(base_addr + 0x8);
}

template <class Tp>
inline __attribute__((always_inline)) void DoNotOptimize(Tp const& value) {
       __asm("fence.i");
}


void fir_hw_memcpy_write_coeff_hw(void* coeff_hw, uint64_t byte_size, uint32_t base_addr) {

    memcpy((void*)(uintptr_t)(base_addr + 0x40), coeff_hw, byte_size);
}

void fir_hw_memcpy_read_coeff_hw(void* coeff_hw, uint64_t byte_size, uint32_t base_addr) {

    memcpy(coeff_hw, (void*)(uintptr_t)(base_addr + 0x40), byte_size);
}

void fir_hw_dma_write_coeff_hw(void* coeff_hw, uint64_t byte_size, uint32_t base_addr){

    // Use DMA to copy input arguments from processor to accelerator.
    hls_memcpy((void*)(uintptr_t)(base_addr + 0x40), (void*)(coeff_hw), byte_size, HLS_ALLOC_MSS_TO_FPGA, HLS_ALLOC_PDMA);

}

void fir_hw_dma_read_coeff_hw(void* coeff_hw, uint64_t byte_size, uint32_t base_addr){

    // Use DMA to copy output arguments from accelerator to processor.
    hls_memcpy((void*)(coeff_hw), (void*)(uintptr_t)(base_addr + 0x40), byte_size, HLS_ALLOC_FPGA_TO_MSS, HLS_ALLOC_PDMA);

}

