SYNTHESIS_TOP_MODULES :=bypass_hw_top
SYNTHESIS_TOP_MODULE :=bypass_hw_top
CUSTOM_TOP_LEVEL :=bypass_hw
ACCELERATOR_NAME :=bypass_hw
TEST_BENCH :=
CUSTOM_TEST_BENCH :=
define SOC_INCOMPATIBLE_INTF

	Function bypass_hw: module control, input_l, input_r, res

endef