# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.srcs/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/cpu_system_smartconnect_0_0.xci
# IP: The module: 'cpu_system_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/bd_7c56.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_1/bd_7c56_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_2/bd_7c56_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_3/bd_7c56_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_4/bd_7c56_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_5/bd_7c56_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_6/bd_7c56_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_7/bd_7c56_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_8/bd_7c56_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_9/bd_7c56_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_10/bd_7c56_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_11/bd_7c56_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_12/bd_7c56_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_1/bd_7c56_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_5/bd_7c56_s00a2s_0_ooc.xdc

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_6/bd_7c56_sarn_0_ooc.xdc

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_7/bd_7c56_srn_0_ooc.xdc

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_8/bd_7c56_sawn_0_ooc.xdc

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_9/bd_7c56_swn_0_ooc.xdc

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_10/bd_7c56_sbn_0_ooc.xdc

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_11/bd_7c56_m00s2a_0_ooc.xdc

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_system_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_system_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.srcs/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/cpu_system_smartconnect_0_0.xci
# IP: The module: 'cpu_system_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/bd_7c56.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_1/bd_7c56_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_2/bd_7c56_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_3/bd_7c56_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_4/bd_7c56_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_5/bd_7c56_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_6/bd_7c56_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_7/bd_7c56_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_8/bd_7c56_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_9/bd_7c56_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_10/bd_7c56_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_11/bd_7c56_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_12/bd_7c56_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_1/bd_7c56_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_5/bd_7c56_s00a2s_0_ooc.xdc

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_6/bd_7c56_sarn_0_ooc.xdc

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_7/bd_7c56_srn_0_ooc.xdc

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_8/bd_7c56_sawn_0_ooc.xdc

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_9/bd_7c56_swn_0_ooc.xdc

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_10/bd_7c56_sbn_0_ooc.xdc

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/bd_0/ip/ip_11/bd_7c56_m00s2a_0_ooc.xdc

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_system_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /mnt/work/fpga_labor/fpga_labor/fpga_labor.gen/sources_1/bd/cpu_system/ip/cpu_system_smartconnect_0_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_system_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
