

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "6", "7", "8", "9", "10"],
		"CDFG" : "fir_hw",
		"Protocol" : "ap_ctrl_none",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "0", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1031",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "tlast_dnum", "Type" : "None", "Direction" : "I"},
			{"Name" : "smpl_rd_num", "Type" : "None", "Direction" : "I"},
			{"Name" : "tap_num_m1", "Type" : "None", "Direction" : "I"},
			{"Name" : "coeff_hw", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "3", "SubInstance" : "grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210", "Port" : "coeff_hw", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "input_l", "Type" : "HS", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "input_l_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "input_r", "Type" : "HS", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "input_r_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "res_V_data_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "res",
				"BlockSignal" : [
					{"Name" : "res_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "res_V_keep_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "res"},
			{"Name" : "res_V_strb_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "res"},
			{"Name" : "res_V_last_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "res"},
			{"Name" : "write_idx", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "buffer_left", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "3", "SubInstance" : "grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210", "Port" : "buffer_left", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "buffer_right", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "3", "SubInstance" : "grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210", "Port" : "buffer_right", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "dec_cnt", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cnt", "Type" : "OVld", "Direction" : "IO"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_left_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_right_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210", "Parent" : "0", "Child" : ["4", "5"],
		"CDFG" : "fir_hw_Pipeline_VITIS_LOOP_32_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "258", "EstimateLatencyMax" : "1026",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "add_ln32", "Type" : "None", "Direction" : "I"},
			{"Name" : "write_idx_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "coeff_hw", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "out_data_data_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "out_data_data_1_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "buffer_left", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_right", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_32_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210.mul_47s_32s_79_1_1_U1", "Parent" : "3"},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210.flow_control_loop_pipe_sequential_init_U", "Parent" : "3"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_res_V_data_V_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_res_V_keep_V_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_res_V_strb_V_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_res_V_last_V_U", "Parent" : "0"}]}
