// This file was autogenerated by SmartHLS on Nov 24 2025, 05:15:47

#pragma GCC diagnostic ignored "-Wpointer-arith"
#include "bypass_hls_accelerator_driver.h"
#include <string.h>
#include <stdio.h>
#include <stdint.h>
#include <unistd.h>

void bypass_hw_write_tlast_dnum(uint16_t val,  uint32_t base_addr) {

    *(volatile uint16_t *)(base_addr + 0x0) = (volatile uint16_t) val;
}

uint16_t bypass_hw_read_tlast_dnum(uint32_t base_addr) {

    return *(volatile uint16_t *)(base_addr + 0x0);
}

