// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="bypass_hw_bypass_hw,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.420000,HLS_SYN_LAT=2,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=96,HLS_SYN_LUT=275,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module bypass_hw (
        ap_clk,
        ap_rst_n,
        input_l,
        input_l_ap_vld,
        input_l_ap_ack,
        input_r,
        input_r_ap_vld,
        input_r_ap_ack,
        res_TDATA,
        res_TVALID,
        res_TREADY,
        res_TKEEP,
        res_TSTRB,
        res_TLAST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [23:0] input_l;
input   input_l_ap_vld;
output   input_l_ap_ack;
input  [23:0] input_r;
input   input_r_ap_vld;
output   input_r_ap_ack;
output  [31:0] res_TDATA;
output   res_TVALID;
input   res_TREADY;
output  [3:0] res_TKEEP;
output  [3:0] res_TSTRB;
output  [0:0] res_TLAST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

reg input_l_ap_ack;
reg input_r_ap_ack;

 reg    ap_rst_n_inv;
wire   [15:0] tlast_dnum;
reg   [15:0] cnt;
reg    input_l_blk_n;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    input_r_blk_n;
reg    res_TDATA_blk_n;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [31:0] out_data_data_fu_118_p3;
wire   [0:0] out_data_last_fu_127_p2;
reg   [23:0] input_r_read_reg_186;
wire   [0:0] out_data_last_1_fu_148_p2;
reg   [0:0] out_data_last_1_reg_191;
wire   [31:0] out_data_data_1_fu_168_p3;
wire   [15:0] select_ln39_fu_154_p3;
reg    ap_block_state1;
wire   [15:0] add_ln22_fu_112_p2;
wire   [15:0] add_ln33_fu_134_p2;
wire   [15:0] select_ln33_fu_140_p3;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    regslice_both_res_V_data_V_U_apdone_blk;
reg    ap_block_state3;
reg   [31:0] res_TDATA_int_regslice;
reg    res_TVALID_int_regslice;
wire    res_TREADY_int_regslice;
wire    regslice_both_res_V_data_V_U_vld_out;
wire    regslice_both_res_V_keep_V_U_apdone_blk;
wire    regslice_both_res_V_keep_V_U_ack_in_dummy;
wire    regslice_both_res_V_keep_V_U_vld_out;
wire    regslice_both_res_V_strb_V_U_apdone_blk;
wire    regslice_both_res_V_strb_V_U_ack_in_dummy;
wire    regslice_both_res_V_strb_V_U_vld_out;
wire    regslice_both_res_V_last_V_U_apdone_blk;
reg   [0:0] res_TLAST_int_regslice;
wire    regslice_both_res_V_last_V_U_ack_in_dummy;
wire    regslice_both_res_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 cnt = 16'd0;
#0 ap_CS_fsm = 3'd1;
end

bypass_hw_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .tlast_dnum(tlast_dnum)
);

bypass_hw_regslice_both #(
    .DataWidth( 32 ))
regslice_both_res_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(res_TDATA_int_regslice),
    .vld_in(res_TVALID_int_regslice),
    .ack_in(res_TREADY_int_regslice),
    .data_out(res_TDATA),
    .vld_out(regslice_both_res_V_data_V_U_vld_out),
    .ack_out(res_TREADY),
    .apdone_blk(regslice_both_res_V_data_V_U_apdone_blk)
);

bypass_hw_regslice_both #(
    .DataWidth( 4 ))
regslice_both_res_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(res_TVALID_int_regslice),
    .ack_in(regslice_both_res_V_keep_V_U_ack_in_dummy),
    .data_out(res_TKEEP),
    .vld_out(regslice_both_res_V_keep_V_U_vld_out),
    .ack_out(res_TREADY),
    .apdone_blk(regslice_both_res_V_keep_V_U_apdone_blk)
);

bypass_hw_regslice_both #(
    .DataWidth( 4 ))
regslice_both_res_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(res_TVALID_int_regslice),
    .ack_in(regslice_both_res_V_strb_V_U_ack_in_dummy),
    .data_out(res_TSTRB),
    .vld_out(regslice_both_res_V_strb_V_U_vld_out),
    .ack_out(res_TREADY),
    .apdone_blk(regslice_both_res_V_strb_V_U_apdone_blk)
);

bypass_hw_regslice_both #(
    .DataWidth( 1 ))
regslice_both_res_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(res_TLAST_int_regslice),
    .vld_in(res_TVALID_int_regslice),
    .ack_in(regslice_both_res_V_last_V_U_ack_in_dummy),
    .data_out(res_TLAST),
    .vld_out(regslice_both_res_V_last_V_U_vld_out),
    .ack_out(res_TREADY),
    .apdone_blk(regslice_both_res_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        cnt <= select_ln39_fu_154_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        input_r_read_reg_186 <= input_r;
        out_data_last_1_reg_191 <= out_data_last_1_fu_148_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((res_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state3)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        input_l_ap_ack = 1'b1;
    end else begin
        input_l_ap_ack = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        input_l_blk_n = input_l_ap_vld;
    end else begin
        input_l_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        input_r_ap_ack = 1'b1;
    end else begin
        input_r_ap_ack = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        input_r_blk_n = input_r_ap_vld;
    end else begin
        input_r_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        res_TDATA_blk_n = res_TREADY_int_regslice;
    end else begin
        res_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (res_TREADY_int_regslice == 1'b1))) begin
        res_TDATA_int_regslice = out_data_data_1_fu_168_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        res_TDATA_int_regslice = out_data_data_fu_118_p3;
    end else begin
        res_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (res_TREADY_int_regslice == 1'b1))) begin
        res_TLAST_int_regslice = out_data_last_1_reg_191;
    end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        res_TLAST_int_regslice = out_data_last_fu_127_p2;
    end else begin
        res_TLAST_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (res_TREADY_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1)))) begin
        res_TVALID_int_regslice = 1'b1;
    end else begin
        res_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (res_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln22_fu_112_p2 = (cnt + 16'd1);

assign add_ln33_fu_134_p2 = (cnt + 16'd2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((res_TREADY_int_regslice == 1'b0) | (input_r_ap_vld == 1'b0) | (input_l_ap_vld == 1'b0));
end

always @ (*) begin
    ap_block_state3 = ((res_TREADY_int_regslice == 1'b0) | (regslice_both_res_V_data_V_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign out_data_data_1_fu_168_p3 = {{input_r_read_reg_186}, {8'd0}};

assign out_data_data_fu_118_p3 = {{input_l}, {8'd0}};

assign out_data_last_1_fu_148_p2 = ((select_ln33_fu_140_p3 == tlast_dnum) ? 1'b1 : 1'b0);

assign out_data_last_fu_127_p2 = ((add_ln22_fu_112_p2 == tlast_dnum) ? 1'b1 : 1'b0);

assign res_TVALID = regslice_both_res_V_data_V_U_vld_out;

assign select_ln33_fu_140_p3 = ((out_data_last_fu_127_p2[0:0] == 1'b1) ? 16'd1 : add_ln33_fu_134_p2);

assign select_ln39_fu_154_p3 = ((out_data_last_1_fu_148_p2[0:0] == 1'b1) ? 16'd0 : select_ln33_fu_140_p3);

endmodule //bypass_hw
