//////////////////////////////////////////////////////////////////////
// Created by SmartDesign Tue Mar  3 20:59:59 2026
// Version: 2025.1 2025.1.0.14
//////////////////////////////////////////////////////////////////////

`timescale 1ns / 100ps

// cpu_system
module cpu_system(
    // Inputs
    REFCLK,
    REFCLK_N,
    REF_CLK_0,
    SD_CD,
    btn,
    // Outputs
    A,
    ACT_N,
    BA,
    BG0,
    CAS_N,
    CK0,
    CK0_N,
    CKE0,
    CS0_N,
    DM,
    ODT0,
    RAS_N,
    RESET_N,
    SD_CLK,
    SD_VOLT_CMD_DIR,
    SD_VOLT_DIR_0,
    SD_VOLT_DIR_1_3,
    SD_VOLT_EN,
    SD_VOLT_SEL,
    WE_N,
    led,
    // Inouts
    DQ,
    DQS,
    DQS_N,
    SD_CMD,
    SD_DATA0,
    SD_DATA1,
    SD_DATA2,
    SD_DATA3
);

//--------------------------------------------------------------------
// Input
//--------------------------------------------------------------------
input         REFCLK;
input         REFCLK_N;
input         REF_CLK_0;
input         SD_CD;
input  [3:0]  btn;
//--------------------------------------------------------------------
// Output
//--------------------------------------------------------------------
output [13:0] A;
output        ACT_N;
output [1:0]  BA;
output        BG0;
output        CAS_N;
output        CK0;
output        CK0_N;
output        CKE0;
output        CS0_N;
output [1:0]  DM;
output        ODT0;
output        RAS_N;
output        RESET_N;
output        SD_CLK;
output        SD_VOLT_CMD_DIR;
output        SD_VOLT_DIR_0;
output        SD_VOLT_DIR_1_3;
output        SD_VOLT_EN;
output        SD_VOLT_SEL;
output        WE_N;
output [3:0]  led;
//--------------------------------------------------------------------
// Inout
//--------------------------------------------------------------------
inout  [15:0] DQ;
inout  [1:0]  DQS;
inout  [1:0]  DQS_N;
inout         SD_CMD;
inout         SD_DATA0;
inout         SD_DATA1;
inout         SD_DATA2;
inout         SD_DATA3;
//--------------------------------------------------------------------
// Nets
//--------------------------------------------------------------------
wire   [13:0] A_net_0;
wire          ACT_N_net_0;
wire   [1:0]  BA_net_0;
wire          BG0_net_0;
wire          CAS_N_net_0;
wire          CK0_net_0;
wire          CK0_N_net_0;
wire          CKE0_net_0;
wire          CoreAPB3_C0_0_APBmslave0_PENABLE;
wire   [31:0] CoreAPB3_C0_0_APBmslave0_PRDATA;
wire          CoreAPB3_C0_0_APBmslave0_PREADY;
wire          CoreAPB3_C0_0_APBmslave0_PSELx;
wire          CoreAPB3_C0_0_APBmslave0_PSLVERR;
wire   [31:0] CoreAPB3_C0_0_APBmslave0_PWDATA;
wire          CoreAPB3_C0_0_APBmslave0_PWRITE;
wire   [1:0]  COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARBURST;
wire   [0:0]  COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARID;
wire   [7:0]  COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARLEN;
wire          COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARREADY;
wire   [2:0]  COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARSIZE;
wire          COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARVALID;
wire   [1:0]  COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWBURST;
wire   [0:0]  COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWID;
wire   [7:0]  COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWLEN;
wire          COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWREADY;
wire   [2:0]  COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWSIZE;
wire          COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWVALID;
wire   [0:0]  COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_BID;
wire          COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_BREADY;
wire   [1:0]  COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_BRESP;
wire   [0:0]  COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_BUSER;
wire          COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_BVALID;
wire   [31:0] COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_RDATA;
wire   [0:0]  COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_RID;
wire          COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_RLAST;
wire          COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_RREADY;
wire   [1:0]  COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_RRESP;
wire   [0:0]  COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_RUSER;
wire          COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_RVALID;
wire   [31:0] COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_WDATA;
wire          COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_WLAST;
wire          COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_WREADY;
wire   [3:0]  COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_WSTRB;
wire          COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_WVALID;
wire   [1:0]  COREAXI4DMACONTROLLER_C0_0_INTERRUPT;
wire   [1:0]  COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARBURST;
wire   [3:0]  COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARCACHE;
wire   [1:0]  COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARID;
wire   [7:0]  COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARLEN;
wire   [1:0]  COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARLOCK;
wire   [2:0]  COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARPROT;
wire   [3:0]  COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARQOS;
wire          COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARREADY;
wire   [3:0]  COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARREGION;
wire   [2:0]  COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARSIZE;
wire   [0:0]  COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARUSER;
wire          COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARVALID;
wire   [1:0]  COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWBURST;
wire   [3:0]  COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWCACHE;
wire   [1:0]  COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWID;
wire   [7:0]  COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWLEN;
wire   [1:0]  COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWLOCK;
wire   [2:0]  COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWPROT;
wire   [3:0]  COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWQOS;
wire          COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWREADY;
wire   [3:0]  COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWREGION;
wire   [2:0]  COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWSIZE;
wire   [0:0]  COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWUSER;
wire          COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWVALID;
wire          COREAXI4INTERCONNECT_C0_0_AXI4mslave0_BREADY;
wire   [1:0]  COREAXI4INTERCONNECT_C0_0_AXI4mslave0_BRESP;
wire          COREAXI4INTERCONNECT_C0_0_AXI4mslave0_BVALID;
wire   [31:0] COREAXI4INTERCONNECT_C0_0_AXI4mslave0_RDATA;
wire          COREAXI4INTERCONNECT_C0_0_AXI4mslave0_RREADY;
wire   [1:0]  COREAXI4INTERCONNECT_C0_0_AXI4mslave0_RRESP;
wire          COREAXI4INTERCONNECT_C0_0_AXI4mslave0_RVALID;
wire   [31:0] COREAXI4INTERCONNECT_C0_0_AXI4mslave0_WDATA;
wire          COREAXI4INTERCONNECT_C0_0_AXI4mslave0_WLAST;
wire          COREAXI4INTERCONNECT_C0_0_AXI4mslave0_WREADY;
wire   [3:0]  COREAXI4INTERCONNECT_C0_0_AXI4mslave0_WSTRB;
wire   [0:0]  COREAXI4INTERCONNECT_C0_0_AXI4mslave0_WUSER;
wire          COREAXI4INTERCONNECT_C0_0_AXI4mslave0_WVALID;
wire   [1:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARBURST;
wire   [3:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARCACHE;
wire   [7:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARLEN;
wire   [2:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARPROT;
wire   [3:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARQOS;
wire          COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARREADY;
wire   [3:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARREGION;
wire   [2:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARSIZE;
wire   [0:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARUSER;
wire          COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARVALID;
wire   [1:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWBURST;
wire   [3:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWCACHE;
wire   [7:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWLEN;
wire   [2:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWPROT;
wire   [3:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWQOS;
wire          COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWREADY;
wire   [3:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWREGION;
wire   [2:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWSIZE;
wire   [0:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWUSER;
wire          COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWVALID;
wire          COREAXI4INTERCONNECT_C1_0_AXI4mslave0_BREADY;
wire   [1:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_BRESP;
wire          COREAXI4INTERCONNECT_C1_0_AXI4mslave0_BVALID;
wire   [63:0] COREAXI4INTERCONNECT_C1_0_AXI4mslave0_RDATA;
wire          COREAXI4INTERCONNECT_C1_0_AXI4mslave0_RLAST;
wire          COREAXI4INTERCONNECT_C1_0_AXI4mslave0_RREADY;
wire   [1:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_RRESP;
wire          COREAXI4INTERCONNECT_C1_0_AXI4mslave0_RVALID;
wire   [63:0] COREAXI4INTERCONNECT_C1_0_AXI4mslave0_WDATA;
wire          COREAXI4INTERCONNECT_C1_0_AXI4mslave0_WLAST;
wire          COREAXI4INTERCONNECT_C1_0_AXI4mslave0_WREADY;
wire   [7:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_WSTRB;
wire   [0:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_WUSER;
wire          COREAXI4INTERCONNECT_C1_0_AXI4mslave0_WVALID;
wire          CORERESET_PF_C0_0_FABRIC_RESET_N;
wire          CS0_N_net_0;
wire   [1:0]  DM_net_0;
wire   [15:0] DQ;
wire   [1:0]  DQS;
wire   [1:0]  DQS_N;
wire   [3:0]  btn;
wire   [3:0]  led_net_0;
wire   [1:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARBURST;
wire   [3:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARCACHE;
wire   [7:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARLEN;
wire   [2:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARPROT;
wire   [3:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARQOS;
wire          MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARREADY;
wire   [2:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARSIZE;
wire          MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARVALID;
wire   [1:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWBURST;
wire   [3:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWCACHE;
wire   [7:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWLEN;
wire   [2:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWPROT;
wire   [3:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWQOS;
wire          MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWREADY;
wire   [2:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWSIZE;
wire          MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWVALID;
wire          MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_BREADY;
wire   [1:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_BRESP;
wire   [0:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_BUSER;
wire          MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_BVALID;
wire   [63:0] MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RDATA;
wire          MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RLAST;
wire          MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RREADY;
wire   [1:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RRESP;
wire   [0:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RUSER;
wire          MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RVALID;
wire   [63:0] MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_WDATA;
wire          MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_WLAST;
wire          MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_WREADY;
wire   [7:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_WSTRB;
wire          MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_WVALID;
wire   [31:0] MPFS_DISCOVERY_KIT_MSS_0_FIC_3_APB_INITIATOR_PADDR;
wire          MPFS_DISCOVERY_KIT_MSS_0_FIC_3_APB_INITIATOR_PENABLE;
wire   [31:0] MPFS_DISCOVERY_KIT_MSS_0_FIC_3_APB_INITIATOR_PRDATA;
wire          MPFS_DISCOVERY_KIT_MSS_0_FIC_3_APB_INITIATOR_PREADY;
wire          MPFS_DISCOVERY_KIT_MSS_0_FIC_3_APB_INITIATOR_PSELx;
wire          MPFS_DISCOVERY_KIT_MSS_0_FIC_3_APB_INITIATOR_PSLVERR;
wire   [31:0] MPFS_DISCOVERY_KIT_MSS_0_FIC_3_APB_INITIATOR_PWDATA;
wire          MPFS_DISCOVERY_KIT_MSS_0_FIC_3_APB_INITIATOR_PWRITE;
wire          MPFS_DISCOVERY_KIT_MSS_0_MSS_RESET_N_M2F;
wire          ODT0_net_0;
wire          PF_CCC_C0_0_OUT0_FABCLK_0;
wire          PF_CCC_C0_0_OUT2_FABCLK_0;
wire          PF_CCC_C0_0_PLL_LOCK_0;
wire          PFSOC_INIT_MONITOR_C0_0_DEVICE_INIT_DONE;
wire          PFSOC_INIT_MONITOR_C0_0_FABRIC_POR_N;
wire          RAS_N_net_0;
wire          REF_CLK_0;
wire          REFCLK;
wire          REFCLK_N;
wire          RESET_N_net_0;
wire          SD_CD;
wire          SD_CLK_net_0;
wire          SD_CMD;
wire          SD_DATA0;
wire          SD_DATA1;
wire          SD_DATA2;
wire          SD_DATA3;
wire          SD_VOLT_CMD_DIR_net_0;
wire          SD_VOLT_DIR_0_net_0;
wire          SD_VOLT_DIR_1_3_net_0;
wire          SD_VOLT_EN_net_0;
wire          SD_VOLT_SEL_net_0;
wire          WE_N_net_0;
wire   [1:0]  BA_net_1;
wire   [1:0]  DM_net_1;
wire   [13:0] A_net_1;
wire          RESET_N_net_1;
wire          CKE0_net_1;
wire          CS0_N_net_1;
wire          ODT0_net_1;
wire          CK0_net_1;
wire          CK0_N_net_1;
wire          RAS_N_net_1;
wire          WE_N_net_1;
wire          CAS_N_net_1;
wire          ACT_N_net_1;
wire          BG0_net_1;
wire          SD_CLK_net_1;
wire          SD_VOLT_SEL_net_1;
wire          SD_VOLT_EN_net_1;
wire          SD_VOLT_CMD_DIR_net_1;
wire          SD_VOLT_DIR_0_net_1;
wire          SD_VOLT_DIR_1_3_net_1;
wire   [3:0]  led_net_1;
wire   [0:0]  INT_slice_0;
wire   [1:1]  INT_slice_1;
wire   [2:2]  INT_slice_2;
wire   [3:3]  INT_slice_3;
wire   [3:0]  INT_net_0;
//--------------------------------------------------------------------
// TiedOff Nets
//--------------------------------------------------------------------
wire   [3:0]  STRTDMAOP_const_net_0;
wire          VCC_net;
wire          GND_net;
wire   [63:0] MSS_INT_F2M_const_net_0;
wire   [1:0]  SLAVE0_BID_const_net_0;
wire   [1:0]  SLAVE0_RID_const_net_0;
wire   [3:0]  MASTER0_AWREGION_const_net_0;
wire   [3:0]  MASTER0_ARREGION_const_net_0;
wire   [1:0]  MASTER0_AWLOCK_const_net_0;
wire   [3:0]  MASTER0_AWCACHE_const_net_0;
wire   [2:0]  MASTER0_AWPROT_const_net_0;
wire   [3:0]  MASTER0_AWQOS_const_net_0;
wire   [3:0]  MASTER0_AWREGION_const_net_1;
wire   [1:0]  MASTER0_ARLOCK_const_net_0;
wire   [3:0]  MASTER0_ARCACHE_const_net_0;
wire   [2:0]  MASTER0_ARPROT_const_net_0;
wire   [3:0]  MASTER0_ARQOS_const_net_0;
wire   [3:0]  MASTER0_ARREGION_const_net_1;
//--------------------------------------------------------------------
// Bus Interface Nets Declarations - Unequal Pin Widths
//--------------------------------------------------------------------
wire   [31:0] CoreAPB3_C0_0_APBmslave0_PADDR;
wire   [7:0]  CoreAPB3_C0_0_APBmslave0_PADDR_0;
wire   [7:0]  CoreAPB3_C0_0_APBmslave0_PADDR_0_7to0;
wire   [31:0] COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARADDR;
wire   [63:0] COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARADDR_0;
wire   [31:0] COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARADDR_0_31to0;
wire   [63:32]COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARADDR_0_63to32;
wire   [31:0] COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWADDR;
wire   [63:0] COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWADDR_0;
wire   [31:0] COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWADDR_0_31to0;
wire   [63:32]COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWADDR_0_63to32;
wire   [63:0] COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARADDR;
wire   [10:0] COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARADDR_0;
wire   [10:0] COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARADDR_0_10to0;
wire   [63:0] COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWADDR;
wire   [10:0] COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWADDR_0;
wire   [10:0] COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWADDR_0_10to0;
wire   [63:0] COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARADDR;
wire   [37:0] COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARADDR_0;
wire   [37:0] COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARADDR_0_37to0;
wire   [1:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARID;
wire   [3:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARID_0;
wire   [1:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARID_0_1to0;
wire   [3:2]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARID_0_3to2;
wire   [1:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARLOCK;
wire          COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARLOCK_0;
wire   [0:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARLOCK_0_0to0;
wire   [63:0] COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWADDR;
wire   [37:0] COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWADDR_0;
wire   [37:0] COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWADDR_0_37to0;
wire   [1:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWID;
wire   [3:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWID_0;
wire   [1:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWID_0_1to0;
wire   [3:2]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWID_0_3to2;
wire   [1:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWLOCK;
wire          COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWLOCK_0;
wire   [0:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWLOCK_0_0to0;
wire   [3:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_BID;
wire   [1:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_BID_0;
wire   [1:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_BID_0_1to0;
wire   [3:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_RID;
wire   [1:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_RID_0;
wire   [1:0]  COREAXI4INTERCONNECT_C1_0_AXI4mslave0_RID_0_1to0;
wire   [37:0] MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARADDR;
wire   [63:0] MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARADDR_0;
wire   [37:0] MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARADDR_0_37to0;
wire   [63:38]MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARADDR_0_63to38;
wire   [7:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARID;
wire   [0:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARID_0;
wire   [0:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARID_0_0to0;
wire          MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARLOCK;
wire   [1:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARLOCK_0;
wire   [0:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARLOCK_0_0to0;
wire   [1:1]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARLOCK_0_1to1;
wire   [37:0] MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWADDR;
wire   [63:0] MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWADDR_0;
wire   [37:0] MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWADDR_0_37to0;
wire   [63:38]MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWADDR_0_63to38;
wire   [7:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWID;
wire   [0:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWID_0;
wire   [0:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWID_0_0to0;
wire          MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWLOCK;
wire   [1:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWLOCK_0;
wire   [0:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWLOCK_0_0to0;
wire   [1:1]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWLOCK_0_1to1;
wire   [0:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_BID;
wire   [7:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_BID_0;
wire   [0:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_BID_0_0to0;
wire   [7:1]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_BID_0_7to1;
wire   [0:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RID;
wire   [7:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RID_0;
wire   [0:0]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RID_0_0to0;
wire   [7:1]  MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RID_0_7to1;
//--------------------------------------------------------------------
// Constant assignments
//--------------------------------------------------------------------
assign STRTDMAOP_const_net_0        = 4'h0;
assign VCC_net                      = 1'b1;
assign GND_net                      = 1'b0;
assign MSS_INT_F2M_const_net_0      = 64'h0000000000000000;
assign SLAVE0_BID_const_net_0       = 2'h0;
assign SLAVE0_RID_const_net_0       = 2'h0;
assign MASTER0_AWREGION_const_net_0 = 4'h0;
assign MASTER0_ARREGION_const_net_0 = 4'h0;
assign MASTER0_AWLOCK_const_net_0   = 2'h0;
assign MASTER0_AWCACHE_const_net_0  = 4'h0;
assign MASTER0_AWPROT_const_net_0   = 3'h0;
assign MASTER0_AWQOS_const_net_0    = 4'h0;
assign MASTER0_AWREGION_const_net_1 = 4'h0;
assign MASTER0_ARLOCK_const_net_0   = 2'h0;
assign MASTER0_ARCACHE_const_net_0  = 4'h0;
assign MASTER0_ARPROT_const_net_0   = 3'h0;
assign MASTER0_ARQOS_const_net_0    = 4'h0;
assign MASTER0_ARREGION_const_net_1 = 4'h0;
//--------------------------------------------------------------------
// Top level output port assignments
//--------------------------------------------------------------------
assign BA_net_1              = BA_net_0;
assign BA[1:0]               = BA_net_1;
assign DM_net_1              = DM_net_0;
assign DM[1:0]               = DM_net_1;
assign A_net_1               = A_net_0;
assign A[13:0]               = A_net_1;
assign RESET_N_net_1         = RESET_N_net_0;
assign RESET_N               = RESET_N_net_1;
assign CKE0_net_1            = CKE0_net_0;
assign CKE0                  = CKE0_net_1;
assign CS0_N_net_1           = CS0_N_net_0;
assign CS0_N                 = CS0_N_net_1;
assign ODT0_net_1            = ODT0_net_0;
assign ODT0                  = ODT0_net_1;
assign CK0_net_1             = CK0_net_0;
assign CK0                   = CK0_net_1;
assign CK0_N_net_1           = CK0_N_net_0;
assign CK0_N                 = CK0_N_net_1;
assign RAS_N_net_1           = RAS_N_net_0;
assign RAS_N                 = RAS_N_net_1;
assign WE_N_net_1            = WE_N_net_0;
assign WE_N                  = WE_N_net_1;
assign CAS_N_net_1           = CAS_N_net_0;
assign CAS_N                 = CAS_N_net_1;
assign ACT_N_net_1           = ACT_N_net_0;
assign ACT_N                 = ACT_N_net_1;
assign BG0_net_1             = BG0_net_0;
assign BG0                   = BG0_net_1;
assign SD_CLK_net_1          = SD_CLK_net_0;
assign SD_CLK                = SD_CLK_net_1;
assign SD_VOLT_SEL_net_1     = SD_VOLT_SEL_net_0;
assign SD_VOLT_SEL           = SD_VOLT_SEL_net_1;
assign SD_VOLT_EN_net_1      = SD_VOLT_EN_net_0;
assign SD_VOLT_EN            = SD_VOLT_EN_net_1;
assign SD_VOLT_CMD_DIR_net_1 = SD_VOLT_CMD_DIR_net_0;
assign SD_VOLT_CMD_DIR       = SD_VOLT_CMD_DIR_net_1;
assign SD_VOLT_DIR_0_net_1   = SD_VOLT_DIR_0_net_0;
assign SD_VOLT_DIR_0         = SD_VOLT_DIR_0_net_1;
assign SD_VOLT_DIR_1_3_net_1 = SD_VOLT_DIR_1_3_net_0;
assign SD_VOLT_DIR_1_3       = SD_VOLT_DIR_1_3_net_1;
assign led_net_1             = led_net_0;
assign led[3:0]              = led_net_1;
//--------------------------------------------------------------------
// Slices assignments
//--------------------------------------------------------------------
assign INT_slice_0[0] = INT_net_0[0:0];
assign INT_slice_1[1] = INT_net_0[1:1];
assign INT_slice_2[2] = INT_net_0[2:2];
assign INT_slice_3[3] = INT_net_0[3:3];
//--------------------------------------------------------------------
// Bus Interface Nets Assignments - Unequal Pin Widths
//--------------------------------------------------------------------
assign CoreAPB3_C0_0_APBmslave0_PADDR_0 = { CoreAPB3_C0_0_APBmslave0_PADDR_0_7to0 };
assign CoreAPB3_C0_0_APBmslave0_PADDR_0_7to0 = CoreAPB3_C0_0_APBmslave0_PADDR[7:0];

assign COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARADDR_0 = { COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARADDR_0_63to32, COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARADDR_0_31to0 };
assign COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARADDR_0_31to0 = COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARADDR[31:0];
assign COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARADDR_0_63to32 = 32'h0;

assign COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWADDR_0 = { COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWADDR_0_63to32, COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWADDR_0_31to0 };
assign COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWADDR_0_31to0 = COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWADDR[31:0];
assign COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWADDR_0_63to32 = 32'h0;

assign COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARADDR_0 = { COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARADDR_0_10to0 };
assign COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARADDR_0_10to0 = COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARADDR[10:0];

assign COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWADDR_0 = { COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWADDR_0_10to0 };
assign COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWADDR_0_10to0 = COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWADDR[10:0];

assign COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARADDR_0 = { COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARADDR_0_37to0 };
assign COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARADDR_0_37to0 = COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARADDR[37:0];

assign COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARID_0 = { COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARID_0_3to2, COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARID_0_1to0 };
assign COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARID_0_1to0 = COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARID[1:0];
assign COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARID_0_3to2 = 2'h0;

assign COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARLOCK_0 = { COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARLOCK_0_0to0 };
assign COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARLOCK_0_0to0 = COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARLOCK[0:0];

assign COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWADDR_0 = { COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWADDR_0_37to0 };
assign COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWADDR_0_37to0 = COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWADDR[37:0];

assign COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWID_0 = { COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWID_0_3to2, COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWID_0_1to0 };
assign COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWID_0_1to0 = COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWID[1:0];
assign COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWID_0_3to2 = 2'h0;

assign COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWLOCK_0 = { COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWLOCK_0_0to0 };
assign COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWLOCK_0_0to0 = COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWLOCK[0:0];

assign COREAXI4INTERCONNECT_C1_0_AXI4mslave0_BID_0 = { COREAXI4INTERCONNECT_C1_0_AXI4mslave0_BID_0_1to0 };
assign COREAXI4INTERCONNECT_C1_0_AXI4mslave0_BID_0_1to0 = COREAXI4INTERCONNECT_C1_0_AXI4mslave0_BID[1:0];

assign COREAXI4INTERCONNECT_C1_0_AXI4mslave0_RID_0 = { COREAXI4INTERCONNECT_C1_0_AXI4mslave0_RID_0_1to0 };
assign COREAXI4INTERCONNECT_C1_0_AXI4mslave0_RID_0_1to0 = COREAXI4INTERCONNECT_C1_0_AXI4mslave0_RID[1:0];

assign MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARADDR_0 = { MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARADDR_0_63to38, MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARADDR_0_37to0 };
assign MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARADDR_0_37to0 = MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARADDR[37:0];
assign MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARADDR_0_63to38 = 26'h0;

assign MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARID_0 = { MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARID_0_0to0 };
assign MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARID_0_0to0 = MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARID[0:0];

assign MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARLOCK_0 = { MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARLOCK_0_1to1, MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARLOCK_0_0to0 };
assign MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARLOCK_0_0to0 = MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARLOCK;
assign MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARLOCK_0_1to1 = 1'b0;

assign MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWADDR_0 = { MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWADDR_0_63to38, MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWADDR_0_37to0 };
assign MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWADDR_0_37to0 = MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWADDR[37:0];
assign MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWADDR_0_63to38 = 26'h0;

assign MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWID_0 = { MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWID_0_0to0 };
assign MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWID_0_0to0 = MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWID[0:0];

assign MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWLOCK_0 = { MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWLOCK_0_1to1, MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWLOCK_0_0to0 };
assign MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWLOCK_0_0to0 = MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWLOCK;
assign MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWLOCK_0_1to1 = 1'b0;

assign MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_BID_0 = { MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_BID_0_7to1, MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_BID_0_0to0 };
assign MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_BID_0_0to0 = MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_BID[0:0];
assign MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_BID_0_7to1 = 7'h0;

assign MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RID_0 = { MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RID_0_7to1, MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RID_0_0to0 };
assign MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RID_0_0to0 = MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RID[0:0];
assign MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RID_0_7to1 = 7'h0;

//--------------------------------------------------------------------
// Component instances
//--------------------------------------------------------------------
//--------CoreAPB3_C0
CoreAPB3_C0 CoreAPB3_C0_0(
        // Inputs
        .PADDR     ( MPFS_DISCOVERY_KIT_MSS_0_FIC_3_APB_INITIATOR_PADDR ),
        .PSEL      ( MPFS_DISCOVERY_KIT_MSS_0_FIC_3_APB_INITIATOR_PSELx ),
        .PENABLE   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_3_APB_INITIATOR_PENABLE ),
        .PWRITE    ( MPFS_DISCOVERY_KIT_MSS_0_FIC_3_APB_INITIATOR_PWRITE ),
        .PWDATA    ( MPFS_DISCOVERY_KIT_MSS_0_FIC_3_APB_INITIATOR_PWDATA ),
        .PRDATAS0  ( CoreAPB3_C0_0_APBmslave0_PRDATA ),
        .PREADYS0  ( CoreAPB3_C0_0_APBmslave0_PREADY ),
        .PSLVERRS0 ( CoreAPB3_C0_0_APBmslave0_PSLVERR ),
        // Outputs
        .PRDATA    ( MPFS_DISCOVERY_KIT_MSS_0_FIC_3_APB_INITIATOR_PRDATA ),
        .PREADY    ( MPFS_DISCOVERY_KIT_MSS_0_FIC_3_APB_INITIATOR_PREADY ),
        .PSLVERR   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_3_APB_INITIATOR_PSLVERR ),
        .PADDRS    ( CoreAPB3_C0_0_APBmslave0_PADDR ),
        .PSELS0    ( CoreAPB3_C0_0_APBmslave0_PSELx ),
        .PENABLES  ( CoreAPB3_C0_0_APBmslave0_PENABLE ),
        .PWRITES   ( CoreAPB3_C0_0_APBmslave0_PWRITE ),
        .PWDATAS   ( CoreAPB3_C0_0_APBmslave0_PWDATA ) 
        );

//--------COREAXI4DMACONTROLLER_C0
COREAXI4DMACONTROLLER_C0 COREAXI4DMACONTROLLER_C0_0(
        // Inputs
        .RESETN       ( CORERESET_PF_C0_0_FABRIC_RESET_N ),
        .CLOCK        ( PF_CCC_C0_0_OUT2_FABCLK_0 ),
        .STRTDMAOP    ( STRTDMAOP_const_net_0 ),
        .DMA_AWREADY  ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWREADY ),
        .DMA_WREADY   ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_WREADY ),
        .DMA_BID      ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_BID ),
        .DMA_BRESP    ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_BRESP ),
        .DMA_BVALID   ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_BVALID ),
        .DMA_ARREADY  ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARREADY ),
        .DMA_RID      ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_RID ),
        .DMA_RDATA    ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_RDATA ),
        .DMA_RRESP    ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_RRESP ),
        .DMA_RLAST    ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_RLAST ),
        .DMA_RVALID   ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_RVALID ),
        .CTRL_AWADDR  ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWADDR_0 ),
        .CTRL_AWVALID ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWVALID ),
        .CTRL_WDATA   ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_WDATA ),
        .CTRL_WSTRB   ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_WSTRB ),
        .CTRL_WVALID  ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_WVALID ),
        .CTRL_BREADY  ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_BREADY ),
        .CTRL_ARADDR  ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARADDR_0 ),
        .CTRL_ARVALID ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARVALID ),
        .CTRL_RREADY  ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_RREADY ),
        // Outputs
        .INTERRUPT    ( COREAXI4DMACONTROLLER_C0_0_INTERRUPT ),
        .DMA_AWID     ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWID ),
        .DMA_AWADDR   ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWADDR ),
        .DMA_AWLEN    ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWLEN ),
        .DMA_AWSIZE   ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWSIZE ),
        .DMA_AWBURST  ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWBURST ),
        .DMA_AWVALID  ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWVALID ),
        .DMA_WDATA    ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_WDATA ),
        .DMA_WSTRB    ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_WSTRB ),
        .DMA_WLAST    ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_WLAST ),
        .DMA_WVALID   ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_WVALID ),
        .DMA_BREADY   ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_BREADY ),
        .DMA_ARID     ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARID ),
        .DMA_ARADDR   ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARADDR ),
        .DMA_ARLEN    ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARLEN ),
        .DMA_ARSIZE   ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARSIZE ),
        .DMA_ARBURST  ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARBURST ),
        .DMA_ARVALID  ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARVALID ),
        .DMA_RREADY   ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_RREADY ),
        .CTRL_AWREADY ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWREADY ),
        .CTRL_WREADY  ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_WREADY ),
        .CTRL_BRESP   ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_BRESP ),
        .CTRL_BVALID  ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_BVALID ),
        .CTRL_ARREADY ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARREADY ),
        .CTRL_RDATA   ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_RDATA ),
        .CTRL_RRESP   ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_RRESP ),
        .CTRL_RVALID  ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_RVALID ) 
        );

//--------COREAXI4INTERCONNECT_C0
COREAXI4INTERCONNECT_C0 COREAXI4INTERCONNECT_C0_0(
        // Inputs
        .ACLK             ( PF_CCC_C0_0_OUT2_FABCLK_0 ),
        .ARESETN          ( CORERESET_PF_C0_0_FABRIC_RESET_N ),
        .SLAVE0_AWREADY   ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWREADY ),
        .SLAVE0_WREADY    ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_WREADY ),
        .SLAVE0_BID       ( SLAVE0_BID_const_net_0 ), // tied to 2'h0 from definition
        .SLAVE0_BRESP     ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_BRESP ),
        .SLAVE0_BVALID    ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_BVALID ),
        .SLAVE0_ARREADY   ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARREADY ),
        .SLAVE0_RID       ( SLAVE0_RID_const_net_0 ), // tied to 2'h0 from definition
        .SLAVE0_RDATA     ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_RDATA ),
        .SLAVE0_RRESP     ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_RRESP ),
        .SLAVE0_RLAST     ( GND_net ), // tied to 1'b0 from definition
        .SLAVE0_RVALID    ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_RVALID ),
        .SLAVE0_BUSER     ( GND_net ), // tied to 1'b0 from definition
        .SLAVE0_RUSER     ( GND_net ), // tied to 1'b0 from definition
        .MASTER0_AWID     ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWID_0 ),
        .MASTER0_AWADDR   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWADDR_0 ),
        .MASTER0_AWLEN    ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWLEN ),
        .MASTER0_AWSIZE   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWSIZE ),
        .MASTER0_AWBURST  ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWBURST ),
        .MASTER0_AWLOCK   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWLOCK_0 ),
        .MASTER0_AWCACHE  ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWCACHE ),
        .MASTER0_AWPROT   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWPROT ),
        .MASTER0_AWQOS    ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWQOS ),
        .MASTER0_AWREGION ( MASTER0_AWREGION_const_net_0 ), // tied to 4'h0 from definition
        .MASTER0_AWVALID  ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWVALID ),
        .MASTER0_WDATA    ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_WDATA ),
        .MASTER0_WSTRB    ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_WSTRB ),
        .MASTER0_WLAST    ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_WLAST ),
        .MASTER0_WVALID   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_WVALID ),
        .MASTER0_BREADY   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_BREADY ),
        .MASTER0_ARID     ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARID_0 ),
        .MASTER0_ARADDR   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARADDR_0 ),
        .MASTER0_ARLEN    ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARLEN ),
        .MASTER0_ARSIZE   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARSIZE ),
        .MASTER0_ARBURST  ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARBURST ),
        .MASTER0_ARLOCK   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARLOCK_0 ),
        .MASTER0_ARCACHE  ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARCACHE ),
        .MASTER0_ARPROT   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARPROT ),
        .MASTER0_ARQOS    ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARQOS ),
        .MASTER0_ARREGION ( MASTER0_ARREGION_const_net_0 ), // tied to 4'h0 from definition
        .MASTER0_ARVALID  ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARVALID ),
        .MASTER0_RREADY   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RREADY ),
        .MASTER0_AWUSER   ( GND_net ), // tied to 1'b0 from definition
        .MASTER0_WUSER    ( GND_net ), // tied to 1'b0 from definition
        .MASTER0_ARUSER   ( GND_net ), // tied to 1'b0 from definition
        // Outputs
        .SLAVE0_AWID      ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWID ),
        .SLAVE0_AWADDR    ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWADDR ),
        .SLAVE0_AWLEN     ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWLEN ),
        .SLAVE0_AWSIZE    ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWSIZE ),
        .SLAVE0_AWBURST   ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWBURST ),
        .SLAVE0_AWLOCK    ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWLOCK ),
        .SLAVE0_AWCACHE   ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWCACHE ),
        .SLAVE0_AWPROT    ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWPROT ),
        .SLAVE0_AWQOS     ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWQOS ),
        .SLAVE0_AWREGION  ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWREGION ),
        .SLAVE0_AWVALID   ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWVALID ),
        .SLAVE0_WDATA     ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_WDATA ),
        .SLAVE0_WSTRB     ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_WSTRB ),
        .SLAVE0_WLAST     ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_WLAST ),
        .SLAVE0_WVALID    ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_WVALID ),
        .SLAVE0_BREADY    ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_BREADY ),
        .SLAVE0_ARID      ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARID ),
        .SLAVE0_ARADDR    ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARADDR ),
        .SLAVE0_ARLEN     ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARLEN ),
        .SLAVE0_ARSIZE    ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARSIZE ),
        .SLAVE0_ARBURST   ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARBURST ),
        .SLAVE0_ARLOCK    ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARLOCK ),
        .SLAVE0_ARCACHE   ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARCACHE ),
        .SLAVE0_ARPROT    ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARPROT ),
        .SLAVE0_ARQOS     ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARQOS ),
        .SLAVE0_ARREGION  ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARREGION ),
        .SLAVE0_ARVALID   ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARVALID ),
        .SLAVE0_RREADY    ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_RREADY ),
        .SLAVE0_AWUSER    ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_AWUSER ),
        .SLAVE0_WUSER     ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_WUSER ),
        .SLAVE0_ARUSER    ( COREAXI4INTERCONNECT_C0_0_AXI4mslave0_ARUSER ),
        .MASTER0_AWREADY  ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWREADY ),
        .MASTER0_WREADY   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_WREADY ),
        .MASTER0_BID      ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_BID ),
        .MASTER0_BRESP    ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_BRESP ),
        .MASTER0_BVALID   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_BVALID ),
        .MASTER0_ARREADY  ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARREADY ),
        .MASTER0_RID      ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RID ),
        .MASTER0_RDATA    ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RDATA ),
        .MASTER0_RRESP    ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RRESP ),
        .MASTER0_RLAST    ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RLAST ),
        .MASTER0_RVALID   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RVALID ),
        .MASTER0_BUSER    ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_BUSER ),
        .MASTER0_RUSER    ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RUSER ) 
        );

//--------COREAXI4INTERCONNECT_C1
COREAXI4INTERCONNECT_C1 COREAXI4INTERCONNECT_C1_0(
        // Inputs
        .ACLK             ( PF_CCC_C0_0_OUT2_FABCLK_0 ),
        .ARESETN          ( CORERESET_PF_C0_0_FABRIC_RESET_N ),
        .SLAVE0_AWREADY   ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWREADY ),
        .SLAVE0_WREADY    ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_WREADY ),
        .SLAVE0_BID       ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_BID_0 ),
        .SLAVE0_BRESP     ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_BRESP ),
        .SLAVE0_BVALID    ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_BVALID ),
        .SLAVE0_ARREADY   ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARREADY ),
        .SLAVE0_RID       ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_RID_0 ),
        .SLAVE0_RDATA     ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_RDATA ),
        .SLAVE0_RRESP     ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_RRESP ),
        .SLAVE0_RLAST     ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_RLAST ),
        .SLAVE0_RVALID    ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_RVALID ),
        .SLAVE0_BUSER     ( GND_net ), // tied to 1'b0 from definition
        .SLAVE0_RUSER     ( GND_net ), // tied to 1'b0 from definition
        .MASTER0_AWID     ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWID ),
        .MASTER0_AWADDR   ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWADDR_0 ),
        .MASTER0_AWLEN    ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWLEN ),
        .MASTER0_AWSIZE   ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWSIZE ),
        .MASTER0_AWBURST  ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWBURST ),
        .MASTER0_AWLOCK   ( MASTER0_AWLOCK_const_net_0 ), // tied to 2'h0 from definition
        .MASTER0_AWCACHE  ( MASTER0_AWCACHE_const_net_0 ), // tied to 4'h0 from definition
        .MASTER0_AWPROT   ( MASTER0_AWPROT_const_net_0 ), // tied to 3'h0 from definition
        .MASTER0_AWQOS    ( MASTER0_AWQOS_const_net_0 ), // tied to 4'h0 from definition
        .MASTER0_AWREGION ( MASTER0_AWREGION_const_net_1 ), // tied to 4'h0 from definition
        .MASTER0_AWVALID  ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWVALID ),
        .MASTER0_WDATA    ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_WDATA ),
        .MASTER0_WSTRB    ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_WSTRB ),
        .MASTER0_WLAST    ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_WLAST ),
        .MASTER0_WVALID   ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_WVALID ),
        .MASTER0_BREADY   ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_BREADY ),
        .MASTER0_ARID     ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARID ),
        .MASTER0_ARADDR   ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARADDR_0 ),
        .MASTER0_ARLEN    ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARLEN ),
        .MASTER0_ARSIZE   ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARSIZE ),
        .MASTER0_ARBURST  ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARBURST ),
        .MASTER0_ARLOCK   ( MASTER0_ARLOCK_const_net_0 ), // tied to 2'h0 from definition
        .MASTER0_ARCACHE  ( MASTER0_ARCACHE_const_net_0 ), // tied to 4'h0 from definition
        .MASTER0_ARPROT   ( MASTER0_ARPROT_const_net_0 ), // tied to 3'h0 from definition
        .MASTER0_ARQOS    ( MASTER0_ARQOS_const_net_0 ), // tied to 4'h0 from definition
        .MASTER0_ARREGION ( MASTER0_ARREGION_const_net_1 ), // tied to 4'h0 from definition
        .MASTER0_ARVALID  ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARVALID ),
        .MASTER0_RREADY   ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_RREADY ),
        .MASTER0_AWUSER   ( GND_net ), // tied to 1'b0 from definition
        .MASTER0_WUSER    ( GND_net ), // tied to 1'b0 from definition
        .MASTER0_ARUSER   ( GND_net ), // tied to 1'b0 from definition
        // Outputs
        .SLAVE0_AWID      ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWID ),
        .SLAVE0_AWADDR    ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWADDR ),
        .SLAVE0_AWLEN     ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWLEN ),
        .SLAVE0_AWSIZE    ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWSIZE ),
        .SLAVE0_AWBURST   ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWBURST ),
        .SLAVE0_AWLOCK    ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWLOCK ),
        .SLAVE0_AWCACHE   ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWCACHE ),
        .SLAVE0_AWPROT    ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWPROT ),
        .SLAVE0_AWQOS     ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWQOS ),
        .SLAVE0_AWREGION  ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWREGION ),
        .SLAVE0_AWVALID   ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWVALID ),
        .SLAVE0_WDATA     ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_WDATA ),
        .SLAVE0_WSTRB     ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_WSTRB ),
        .SLAVE0_WLAST     ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_WLAST ),
        .SLAVE0_WVALID    ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_WVALID ),
        .SLAVE0_BREADY    ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_BREADY ),
        .SLAVE0_ARID      ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARID ),
        .SLAVE0_ARADDR    ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARADDR ),
        .SLAVE0_ARLEN     ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARLEN ),
        .SLAVE0_ARSIZE    ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARSIZE ),
        .SLAVE0_ARBURST   ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARBURST ),
        .SLAVE0_ARLOCK    ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARLOCK ),
        .SLAVE0_ARCACHE   ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARCACHE ),
        .SLAVE0_ARPROT    ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARPROT ),
        .SLAVE0_ARQOS     ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARQOS ),
        .SLAVE0_ARREGION  ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARREGION ),
        .SLAVE0_ARVALID   ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARVALID ),
        .SLAVE0_RREADY    ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_RREADY ),
        .SLAVE0_AWUSER    ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWUSER ),
        .SLAVE0_WUSER     ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_WUSER ),
        .SLAVE0_ARUSER    ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARUSER ),
        .MASTER0_AWREADY  ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_AWREADY ),
        .MASTER0_WREADY   ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_WREADY ),
        .MASTER0_BID      ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_BID ),
        .MASTER0_BRESP    ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_BRESP ),
        .MASTER0_BVALID   ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_BVALID ),
        .MASTER0_ARREADY  ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_ARREADY ),
        .MASTER0_RID      ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_RID ),
        .MASTER0_RDATA    ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_RDATA ),
        .MASTER0_RRESP    ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_RRESP ),
        .MASTER0_RLAST    ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_RLAST ),
        .MASTER0_RVALID   ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_RVALID ),
        .MASTER0_BUSER    ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_BUSER ),
        .MASTER0_RUSER    ( COREAXI4DMACONTROLLER_C0_0_AXI4InitiatorDMA_IF_RUSER ) 
        );

//--------CoreGPIO_C0
CoreGPIO_C0 CoreGPIO_C0_0(
        // Inputs
        .PRESETN  ( CORERESET_PF_C0_0_FABRIC_RESET_N ),
        .PCLK     ( PF_CCC_C0_0_OUT2_FABCLK_0 ),
        .GPIO_IN  ( btn ),
        .PADDR    ( CoreAPB3_C0_0_APBmslave0_PADDR_0 ),
        .PSEL     ( CoreAPB3_C0_0_APBmslave0_PSELx ),
        .PENABLE  ( CoreAPB3_C0_0_APBmslave0_PENABLE ),
        .PWRITE   ( CoreAPB3_C0_0_APBmslave0_PWRITE ),
        .PWDATA   ( CoreAPB3_C0_0_APBmslave0_PWDATA ),
        // Outputs
        .INT      ( INT_net_0 ),
        .GPIO_OUT ( led_net_0 ),
        .GPIO_OE  (  ),
        .PRDATA   ( CoreAPB3_C0_0_APBmslave0_PRDATA ),
        .PREADY   ( CoreAPB3_C0_0_APBmslave0_PREADY ),
        .PSLVERR  ( CoreAPB3_C0_0_APBmslave0_PSLVERR ) 
        );

//--------CORERESET_PF_C0
CORERESET_PF_C0 CORERESET_PF_C0_0(
        // Inputs
        .CLK                ( PF_CCC_C0_0_OUT0_FABCLK_0 ),
        .EXT_RST_N          ( MPFS_DISCOVERY_KIT_MSS_0_MSS_RESET_N_M2F ),
        .BANK_x_VDDI_STATUS ( VCC_net ),
        .BANK_y_VDDI_STATUS ( VCC_net ),
        .PLL_LOCK           ( PF_CCC_C0_0_PLL_LOCK_0 ),
        .SS_BUSY            ( GND_net ),
        .INIT_DONE          ( PFSOC_INIT_MONITOR_C0_0_DEVICE_INIT_DONE ),
        .FF_US_RESTORE      ( GND_net ),
        .FPGA_POR_N         ( PFSOC_INIT_MONITOR_C0_0_FABRIC_POR_N ),
        // Outputs
        .PLL_POWERDOWN_B    (  ),
        .FABRIC_RESET_N     ( CORERESET_PF_C0_0_FABRIC_RESET_N ) 
        );

//--------MPFS_DISCOVERY_KIT_MSS
MPFS_DISCOVERY_KIT_MSS MPFS_DISCOVERY_KIT_MSS_0(
        // Inputs
        .FIC_0_ACLK           ( PF_CCC_C0_0_OUT0_FABCLK_0 ),
        .FIC_0_AXI4_S_AWID    ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWID_0 ),
        .FIC_0_AXI4_S_AWADDR  ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWADDR_0 ),
        .FIC_0_AXI4_S_AWLEN   ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWLEN ),
        .FIC_0_AXI4_S_AWSIZE  ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWSIZE ),
        .FIC_0_AXI4_S_AWBURST ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWBURST ),
        .FIC_0_AXI4_S_AWQOS   ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWQOS ),
        .FIC_0_AXI4_S_AWLOCK  ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWLOCK_0 ),
        .FIC_0_AXI4_S_AWCACHE ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWCACHE ),
        .FIC_0_AXI4_S_AWPROT  ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWPROT ),
        .FIC_0_AXI4_S_AWVALID ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWVALID ),
        .FIC_0_AXI4_S_WDATA   ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_WDATA ),
        .FIC_0_AXI4_S_WSTRB   ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_WSTRB ),
        .FIC_0_AXI4_S_WLAST   ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_WLAST ),
        .FIC_0_AXI4_S_WVALID  ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_WVALID ),
        .FIC_0_AXI4_S_BREADY  ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_BREADY ),
        .FIC_0_AXI4_S_ARID    ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARID_0 ),
        .FIC_0_AXI4_S_ARADDR  ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARADDR_0 ),
        .FIC_0_AXI4_S_ARLEN   ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARLEN ),
        .FIC_0_AXI4_S_ARSIZE  ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARSIZE ),
        .FIC_0_AXI4_S_ARBURST ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARBURST ),
        .FIC_0_AXI4_S_ARQOS   ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARQOS ),
        .FIC_0_AXI4_S_ARLOCK  ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARLOCK_0 ),
        .FIC_0_AXI4_S_ARCACHE ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARCACHE ),
        .FIC_0_AXI4_S_ARPROT  ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARPROT ),
        .FIC_0_AXI4_S_ARVALID ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARVALID ),
        .FIC_0_AXI4_S_RREADY  ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_RREADY ),
        .FIC_1_ACLK           ( PF_CCC_C0_0_OUT0_FABCLK_0 ),
        .FIC_1_AXI4_M_AWREADY ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWREADY ),
        .FIC_1_AXI4_M_WREADY  ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_WREADY ),
        .FIC_1_AXI4_M_BID     ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_BID_0 ),
        .FIC_1_AXI4_M_BRESP   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_BRESP ),
        .FIC_1_AXI4_M_BVALID  ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_BVALID ),
        .FIC_1_AXI4_M_ARREADY ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARREADY ),
        .FIC_1_AXI4_M_RID     ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RID_0 ),
        .FIC_1_AXI4_M_RDATA   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RDATA ),
        .FIC_1_AXI4_M_RRESP   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RRESP ),
        .FIC_1_AXI4_M_RLAST   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RLAST ),
        .FIC_1_AXI4_M_RVALID  ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RVALID ),
        .FIC_3_PCLK           ( PF_CCC_C0_0_OUT2_FABCLK_0 ),
        .FIC_3_APB_M_PRDATA   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_3_APB_INITIATOR_PRDATA ),
        .FIC_3_APB_M_PREADY   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_3_APB_INITIATOR_PREADY ),
        .FIC_3_APB_M_PSLVERR  ( MPFS_DISCOVERY_KIT_MSS_0_FIC_3_APB_INITIATOR_PSLVERR ),
        .MSS_INT_F2M          ( MSS_INT_F2M_const_net_0 ),
        .MSS_RESET_N_F2M      ( VCC_net ),
        .SD_CD                ( SD_CD ),
        .REFCLK               ( REFCLK ),
        .REFCLK_N             ( REFCLK_N ),
        // Outputs
        .FIC_0_DLL_LOCK_M2F   (  ),
        .FIC_1_DLL_LOCK_M2F   (  ),
        .FIC_3_DLL_LOCK_M2F   (  ),
        .FIC_0_AXI4_S_AWREADY ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_AWREADY ),
        .FIC_0_AXI4_S_WREADY  ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_WREADY ),
        .FIC_0_AXI4_S_BID     ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_BID ),
        .FIC_0_AXI4_S_BRESP   ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_BRESP ),
        .FIC_0_AXI4_S_BVALID  ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_BVALID ),
        .FIC_0_AXI4_S_ARREADY ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_ARREADY ),
        .FIC_0_AXI4_S_RID     ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_RID ),
        .FIC_0_AXI4_S_RDATA   ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_RDATA ),
        .FIC_0_AXI4_S_RRESP   ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_RRESP ),
        .FIC_0_AXI4_S_RLAST   ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_RLAST ),
        .FIC_0_AXI4_S_RVALID  ( COREAXI4INTERCONNECT_C1_0_AXI4mslave0_RVALID ),
        .FIC_1_AXI4_M_AWID    ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWID ),
        .FIC_1_AXI4_M_AWADDR  ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWADDR ),
        .FIC_1_AXI4_M_AWLEN   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWLEN ),
        .FIC_1_AXI4_M_AWSIZE  ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWSIZE ),
        .FIC_1_AXI4_M_AWBURST ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWBURST ),
        .FIC_1_AXI4_M_AWLOCK  ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWLOCK ),
        .FIC_1_AXI4_M_AWQOS   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWQOS ),
        .FIC_1_AXI4_M_AWCACHE ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWCACHE ),
        .FIC_1_AXI4_M_AWPROT  ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWPROT ),
        .FIC_1_AXI4_M_AWVALID ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_AWVALID ),
        .FIC_1_AXI4_M_WDATA   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_WDATA ),
        .FIC_1_AXI4_M_WSTRB   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_WSTRB ),
        .FIC_1_AXI4_M_WLAST   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_WLAST ),
        .FIC_1_AXI4_M_WVALID  ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_WVALID ),
        .FIC_1_AXI4_M_BREADY  ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_BREADY ),
        .FIC_1_AXI4_M_ARID    ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARID ),
        .FIC_1_AXI4_M_ARADDR  ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARADDR ),
        .FIC_1_AXI4_M_ARLEN   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARLEN ),
        .FIC_1_AXI4_M_ARSIZE  ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARSIZE ),
        .FIC_1_AXI4_M_ARBURST ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARBURST ),
        .FIC_1_AXI4_M_ARLOCK  ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARLOCK ),
        .FIC_1_AXI4_M_ARQOS   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARQOS ),
        .FIC_1_AXI4_M_ARCACHE ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARCACHE ),
        .FIC_1_AXI4_M_ARPROT  ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARPROT ),
        .FIC_1_AXI4_M_ARVALID ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_ARVALID ),
        .FIC_1_AXI4_M_RREADY  ( MPFS_DISCOVERY_KIT_MSS_0_FIC_1_AXI4_INITIATOR_RREADY ),
        .FIC_3_APB_M_PSEL     ( MPFS_DISCOVERY_KIT_MSS_0_FIC_3_APB_INITIATOR_PSELx ),
        .FIC_3_APB_M_PADDR    ( MPFS_DISCOVERY_KIT_MSS_0_FIC_3_APB_INITIATOR_PADDR ),
        .FIC_3_APB_M_PWRITE   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_3_APB_INITIATOR_PWRITE ),
        .FIC_3_APB_M_PENABLE  ( MPFS_DISCOVERY_KIT_MSS_0_FIC_3_APB_INITIATOR_PENABLE ),
        .FIC_3_APB_M_PSTRB    (  ),
        .FIC_3_APB_M_PWDATA   ( MPFS_DISCOVERY_KIT_MSS_0_FIC_3_APB_INITIATOR_PWDATA ),
        .MSS_INT_M2F          (  ),
        .PLL_CPU_LOCK_M2F     (  ),
        .PLL_DDR_LOCK_M2F     (  ),
        .MSS_RESET_N_M2F      ( MPFS_DISCOVERY_KIT_MSS_0_MSS_RESET_N_M2F ),
        .SD_CLK               ( SD_CLK_net_0 ),
        .SD_VOLT_SEL          ( SD_VOLT_SEL_net_0 ),
        .SD_VOLT_EN           ( SD_VOLT_EN_net_0 ),
        .SD_VOLT_CMD_DIR      ( SD_VOLT_CMD_DIR_net_0 ),
        .SD_VOLT_DIR_0        ( SD_VOLT_DIR_0_net_0 ),
        .SD_VOLT_DIR_1_3      ( SD_VOLT_DIR_1_3_net_0 ),
        .BA                   ( BA_net_0 ),
        .DM                   ( DM_net_0 ),
        .A                    ( A_net_0 ),
        .RESET_N              ( RESET_N_net_0 ),
        .CKE0                 ( CKE0_net_0 ),
        .CS0_N                ( CS0_N_net_0 ),
        .ODT0                 ( ODT0_net_0 ),
        .CK0                  ( CK0_net_0 ),
        .CK0_N                ( CK0_N_net_0 ),
        .RAS_N                ( RAS_N_net_0 ),
        .WE_N                 ( WE_N_net_0 ),
        .CAS_N                ( CAS_N_net_0 ),
        .ACT_N                ( ACT_N_net_0 ),
        .BG0                  ( BG0_net_0 ),
        // Inouts
        .SD_CMD               ( SD_CMD ),
        .SD_DATA0             ( SD_DATA0 ),
        .SD_DATA1             ( SD_DATA1 ),
        .SD_DATA2             ( SD_DATA2 ),
        .SD_DATA3             ( SD_DATA3 ),
        .DQ                   ( DQ ),
        .DQS                  ( DQS ),
        .DQS_N                ( DQS_N ) 
        );

//--------PF_CCC_C0
PF_CCC_C0 PF_CCC_C0_0(
        // Inputs
        .REF_CLK_0         ( REF_CLK_0 ),
        .PLL_POWERDOWN_N_0 ( VCC_net ),
        // Outputs
        .OUT0_FABCLK_0     ( PF_CCC_C0_0_OUT0_FABCLK_0 ),
        .OUT2_FABCLK_0     ( PF_CCC_C0_0_OUT2_FABCLK_0 ),
        .PLL_LOCK_0        ( PF_CCC_C0_0_PLL_LOCK_0 ) 
        );

//--------PFSOC_INIT_MONITOR_C0
PFSOC_INIT_MONITOR_C0 PFSOC_INIT_MONITOR_C0_0(
        // Outputs
        .FABRIC_POR_N               ( PFSOC_INIT_MONITOR_C0_0_FABRIC_POR_N ),
        .PCIE_INIT_DONE             (  ),
        .USRAM_INIT_DONE            (  ),
        .SRAM_INIT_DONE             (  ),
        .DEVICE_INIT_DONE           ( PFSOC_INIT_MONITOR_C0_0_DEVICE_INIT_DONE ),
        .XCVR_INIT_DONE             (  ),
        .USRAM_INIT_FROM_SNVM_DONE  (  ),
        .USRAM_INIT_FROM_UPROM_DONE (  ),
        .USRAM_INIT_FROM_SPI_DONE   (  ),
        .SRAM_INIT_FROM_SNVM_DONE   (  ),
        .SRAM_INIT_FROM_UPROM_DONE  (  ),
        .SRAM_INIT_FROM_SPI_DONE    (  ),
        .AUTOCALIB_DONE             (  ) 
        );


endmodule
