-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fir_hw is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 12;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    input_l : IN STD_LOGIC_VECTOR (23 downto 0);
    input_l_ap_vld : IN STD_LOGIC;
    input_l_ap_ack : OUT STD_LOGIC;
    input_r : IN STD_LOGIC_VECTOR (23 downto 0);
    input_r_ap_vld : IN STD_LOGIC;
    input_r_ap_ack : OUT STD_LOGIC;
    res_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    res_TVALID : OUT STD_LOGIC;
    res_TREADY : IN STD_LOGIC;
    res_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    res_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    res_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of fir_hw is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fir_hw_fir_hw,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.764300,HLS_SYN_LAT=324,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=495,HLS_SYN_LUT=867,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv16_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000010";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";

    signal ap_rst_n_inv : STD_LOGIC;
    signal tlast_dnum : STD_LOGIC_VECTOR (15 downto 0);
    signal smpl_rd_num : STD_LOGIC_VECTOR (2 downto 0);
    signal tap_num_m1 : STD_LOGIC_VECTOR (8 downto 0);
    signal coeff_hw_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal write_idx : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal buffer_left_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal buffer_left_ce0 : STD_LOGIC;
    signal buffer_left_q0 : STD_LOGIC_VECTOR (23 downto 0);
    signal buffer_right_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal buffer_right_ce0 : STD_LOGIC;
    signal buffer_right_q0 : STD_LOGIC_VECTOR (23 downto 0);
    signal dec_cnt : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal cnt : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_l_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal input_r_blk_n : STD_LOGIC;
    signal res_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal icmp_ln26_reg_360 : STD_LOGIC_VECTOR (0 downto 0);
    signal tap_num_m1_read_reg_335 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln25_fu_238_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln26_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_data_last_fu_260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_data_last_reg_364 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_data_last_1_fu_280_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_data_last_1_reg_369 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln32_fu_303_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln32_reg_374 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_start : STD_LOGIC;
    signal grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_done : STD_LOGIC;
    signal grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_idle : STD_LOGIC;
    signal grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_ready : STD_LOGIC;
    signal grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_coeff_hw_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_coeff_hw_ce0 : STD_LOGIC;
    signal grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_out_data_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_out_data_data_out_ap_vld : STD_LOGIC;
    signal grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_out_data_data_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_out_data_data_1_out_ap_vld : STD_LOGIC;
    signal grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_left_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_left_ce0 : STD_LOGIC;
    signal grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_right_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_right_ce0 : STD_LOGIC;
    signal ap_phi_mux_dec_cnt_new_0_phi_fu_203_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal dec_cnt_new_0_reg_200 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal regslice_both_res_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state6 : BOOLEAN;
    signal grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal zext_ln22_fu_228_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln65_fu_318_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln60_fu_286_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal buffer_left_we0_local : STD_LOGIC;
    signal buffer_left_ce0_local : STD_LOGIC;
    signal buffer_right_we0_local : STD_LOGIC;
    signal buffer_right_ce0_local : STD_LOGIC;
    signal add_ln43_fu_254_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln54_fu_266_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln54_fu_272_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln32_fu_300_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal res_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal res_TVALID_int_regslice : STD_LOGIC;
    signal res_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_res_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_res_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_res_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_res_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_res_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_res_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_res_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_res_V_last_V_U_apdone_blk : STD_LOGIC;
    signal res_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_res_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_res_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fir_hw_fir_hw_Pipeline_VITIS_LOOP_32_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        add_ln32 : IN STD_LOGIC_VECTOR (9 downto 0);
        write_idx_load : IN STD_LOGIC_VECTOR (8 downto 0);
        coeff_hw_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        coeff_hw_ce0 : OUT STD_LOGIC;
        coeff_hw_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_data_data_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_data_data_out_ap_vld : OUT STD_LOGIC;
        out_data_data_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_data_data_1_out_ap_vld : OUT STD_LOGIC;
        buffer_left_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        buffer_left_ce0 : OUT STD_LOGIC;
        buffer_left_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
        buffer_right_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        buffer_right_ce0 : OUT STD_LOGIC;
        buffer_right_q0 : IN STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component fir_hw_buffer_left_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (23 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component fir_hw_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        tlast_dnum : OUT STD_LOGIC_VECTOR (15 downto 0);
        smpl_rd_num : OUT STD_LOGIC_VECTOR (2 downto 0);
        tap_num_m1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        coeff_hw_address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        coeff_hw_ce0 : IN STD_LOGIC;
        coeff_hw_q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fir_hw_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    buffer_left_U : component fir_hw_buffer_left_RAM_AUTO_1R1W
    generic map (
        DataWidth => 24,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => buffer_left_address0,
        ce0 => buffer_left_ce0,
        we0 => buffer_left_we0_local,
        d0 => input_l,
        q0 => buffer_left_q0);

    buffer_right_U : component fir_hw_buffer_left_RAM_AUTO_1R1W
    generic map (
        DataWidth => 24,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => buffer_right_address0,
        ce0 => buffer_right_ce0,
        we0 => buffer_right_we0_local,
        d0 => input_r,
        q0 => buffer_right_q0);

    grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210 : component fir_hw_fir_hw_Pipeline_VITIS_LOOP_32_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_start,
        ap_done => grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_done,
        ap_idle => grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_idle,
        ap_ready => grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_ready,
        add_ln32 => add_ln32_reg_374,
        write_idx_load => write_idx,
        coeff_hw_address0 => grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_coeff_hw_address0,
        coeff_hw_ce0 => grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_coeff_hw_ce0,
        coeff_hw_q0 => coeff_hw_q0,
        out_data_data_out => grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_out_data_data_out,
        out_data_data_out_ap_vld => grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_out_data_data_out_ap_vld,
        out_data_data_1_out => grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_out_data_data_1_out,
        out_data_data_1_out_ap_vld => grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_out_data_data_1_out_ap_vld,
        buffer_left_address0 => grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_left_address0,
        buffer_left_ce0 => grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_left_ce0,
        buffer_left_q0 => buffer_left_q0,
        buffer_right_address0 => grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_right_address0,
        buffer_right_ce0 => grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_right_ce0,
        buffer_right_q0 => buffer_right_q0);

    control_s_axi_U : component fir_hw_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        tlast_dnum => tlast_dnum,
        smpl_rd_num => smpl_rd_num,
        tap_num_m1 => tap_num_m1,
        coeff_hw_address0 => grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_coeff_hw_address0,
        coeff_hw_ce0 => grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_coeff_hw_ce0,
        coeff_hw_q0 => coeff_hw_q0);

    regslice_both_res_V_data_V_U : component fir_hw_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => res_TDATA_int_regslice,
        vld_in => res_TVALID_int_regslice,
        ack_in => res_TREADY_int_regslice,
        data_out => res_TDATA,
        vld_out => regslice_both_res_V_data_V_U_vld_out,
        ack_out => res_TREADY,
        apdone_blk => regslice_both_res_V_data_V_U_apdone_blk);

    regslice_both_res_V_keep_V_U : component fir_hw_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => res_TVALID_int_regslice,
        ack_in => regslice_both_res_V_keep_V_U_ack_in_dummy,
        data_out => res_TKEEP,
        vld_out => regslice_both_res_V_keep_V_U_vld_out,
        ack_out => res_TREADY,
        apdone_blk => regslice_both_res_V_keep_V_U_apdone_blk);

    regslice_both_res_V_strb_V_U : component fir_hw_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => res_TVALID_int_regslice,
        ack_in => regslice_both_res_V_strb_V_U_ack_in_dummy,
        data_out => res_TSTRB,
        vld_out => regslice_both_res_V_strb_V_U_vld_out,
        ack_out => res_TREADY,
        apdone_blk => regslice_both_res_V_strb_V_U_apdone_blk);

    regslice_both_res_V_last_V_U : component fir_hw_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => res_TLAST_int_regslice,
        vld_in => res_TVALID_int_regslice,
        ack_in => regslice_both_res_V_last_V_U_ack_in_dummy,
        data_out => res_TLAST,
        vld_out => regslice_both_res_V_last_V_U_vld_out,
        ack_out => res_TREADY,
        apdone_blk => regslice_both_res_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_ready = ap_const_logic_1)) then 
                    grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    dec_cnt_new_0_reg_200_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln26_reg_360 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_boolean_0 = ap_block_state6))) then 
                dec_cnt_new_0_reg_200 <= ap_const_lv3_0;
            elsif (((icmp_ln26_fu_244_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                dec_cnt_new_0_reg_200 <= add_ln25_fu_238_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln32_reg_374 <= add_ln32_fu_303_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln26_fu_244_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                cnt <= select_ln60_fu_286_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_boolean_0 = ap_block_state6))) then
                dec_cnt <= ap_phi_mux_dec_cnt_new_0_phi_fu_203_p4;
                write_idx <= add_ln65_fu_318_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                icmp_ln26_reg_360 <= icmp_ln26_fu_244_p2;
                out_data_last_1_reg_369 <= out_data_last_1_fu_280_p2;
                out_data_last_reg_364 <= out_data_last_fu_260_p2;
                tap_num_m1_read_reg_335 <= tap_num_m1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, icmp_ln26_fu_244_p2, grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_done, ap_block_state1, ap_block_state6, ap_CS_fsm_state3, res_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((icmp_ln26_fu_244_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                elsif (((icmp_ln26_fu_244_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((res_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((res_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_boolean_0 = ap_block_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln25_fu_238_p2 <= std_logic_vector(unsigned(dec_cnt) + unsigned(ap_const_lv3_1));
    add_ln32_fu_303_p2 <= std_logic_vector(unsigned(zext_ln32_fu_300_p1) + unsigned(ap_const_lv10_1));
    add_ln43_fu_254_p2 <= std_logic_vector(unsigned(cnt) + unsigned(ap_const_lv16_1));
    add_ln54_fu_266_p2 <= std_logic_vector(unsigned(cnt) + unsigned(ap_const_lv16_2));
    add_ln65_fu_318_p2 <= std_logic_vector(unsigned(write_idx) + unsigned(ap_const_lv9_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_done)
    begin
        if ((grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(res_TREADY_int_regslice)
    begin
        if ((res_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(res_TREADY_int_regslice)
    begin
        if ((res_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state6_blk_assign_proc : process(ap_block_state6)
    begin
        if ((ap_const_boolean_1 = ap_block_state6)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(input_l_ap_vld, input_r_ap_vld)
    begin
                ap_block_state1 <= ((input_r_ap_vld = ap_const_logic_0) or (input_l_ap_vld = ap_const_logic_0));
    end process;


    ap_block_state6_assign_proc : process(icmp_ln26_reg_360, regslice_both_res_V_data_V_U_apdone_blk, res_TREADY_int_regslice)
    begin
                ap_block_state6 <= ((regslice_both_res_V_data_V_U_apdone_blk = ap_const_logic_1) or ((icmp_ln26_reg_360 = ap_const_lv1_0) and (res_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_phi_mux_dec_cnt_new_0_phi_fu_203_p4_assign_proc : process(ap_CS_fsm_state6, icmp_ln26_reg_360, dec_cnt_new_0_reg_200)
    begin
        if (((icmp_ln26_reg_360 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_phi_mux_dec_cnt_new_0_phi_fu_203_p4 <= ap_const_lv3_0;
        else 
            ap_phi_mux_dec_cnt_new_0_phi_fu_203_p4 <= dec_cnt_new_0_reg_200;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    buffer_left_address0_assign_proc : process(grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_left_address0, ap_CS_fsm_state3, zext_ln22_fu_228_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            buffer_left_address0 <= grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_left_address0;
        else 
            buffer_left_address0 <= zext_ln22_fu_228_p1(9 - 1 downto 0);
        end if; 
    end process;


    buffer_left_ce0_assign_proc : process(grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_left_ce0, ap_CS_fsm_state3, buffer_left_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            buffer_left_ce0 <= grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_left_ce0;
        else 
            buffer_left_ce0 <= buffer_left_ce0_local;
        end if; 
    end process;


    buffer_left_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            buffer_left_ce0_local <= ap_const_logic_1;
        else 
            buffer_left_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    buffer_left_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            buffer_left_we0_local <= ap_const_logic_1;
        else 
            buffer_left_we0_local <= ap_const_logic_0;
        end if; 
    end process;


    buffer_right_address0_assign_proc : process(grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_right_address0, ap_CS_fsm_state3, zext_ln22_fu_228_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            buffer_right_address0 <= grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_right_address0;
        else 
            buffer_right_address0 <= zext_ln22_fu_228_p1(9 - 1 downto 0);
        end if; 
    end process;


    buffer_right_ce0_assign_proc : process(grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_right_ce0, ap_CS_fsm_state3, buffer_right_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            buffer_right_ce0 <= grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_buffer_right_ce0;
        else 
            buffer_right_ce0 <= buffer_right_ce0_local;
        end if; 
    end process;


    buffer_right_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            buffer_right_ce0_local <= ap_const_logic_1;
        else 
            buffer_right_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    buffer_right_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            buffer_right_we0_local <= ap_const_logic_1;
        else 
            buffer_right_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_start <= grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_ap_start_reg;
    icmp_ln26_fu_244_p2 <= "1" when (unsigned(add_ln25_fu_238_p2) < unsigned(smpl_rd_num)) else "0";

    input_l_ap_ack_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            input_l_ap_ack <= ap_const_logic_1;
        else 
            input_l_ap_ack <= ap_const_logic_0;
        end if; 
    end process;


    input_l_blk_n_assign_proc : process(input_l_ap_vld, ap_CS_fsm_state1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            input_l_blk_n <= input_l_ap_vld;
        else 
            input_l_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    input_r_ap_ack_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            input_r_ap_ack <= ap_const_logic_1;
        else 
            input_r_ap_ack <= ap_const_logic_0;
        end if; 
    end process;


    input_r_blk_n_assign_proc : process(input_r_ap_vld, ap_CS_fsm_state1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            input_r_blk_n <= input_r_ap_vld;
        else 
            input_r_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_data_last_1_fu_280_p2 <= "1" when (select_ln54_fu_272_p3 = tlast_dnum) else "0";
    out_data_last_fu_260_p2 <= "1" when (add_ln43_fu_254_p2 = tlast_dnum) else "0";

    res_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, icmp_ln26_reg_360, res_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or ((icmp_ln26_reg_360 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            res_TDATA_blk_n <= res_TREADY_int_regslice;
        else 
            res_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    res_TDATA_int_regslice_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_out_data_data_out, grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_out_data_data_1_out, res_TREADY_int_regslice)
    begin
        if ((res_TREADY_int_regslice = ap_const_logic_1)) then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                res_TDATA_int_regslice <= grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_out_data_data_1_out;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                res_TDATA_int_regslice <= grp_fir_hw_Pipeline_VITIS_LOOP_32_1_fu_210_out_data_data_out;
            else 
                res_TDATA_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            res_TDATA_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    res_TLAST_int_regslice_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, out_data_last_reg_364, out_data_last_1_reg_369, res_TREADY_int_regslice)
    begin
        if ((res_TREADY_int_regslice = ap_const_logic_1)) then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                res_TLAST_int_regslice <= out_data_last_1_reg_369;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                res_TLAST_int_regslice <= out_data_last_reg_364;
            else 
                res_TLAST_int_regslice <= "X";
            end if;
        else 
            res_TLAST_int_regslice <= "X";
        end if; 
    end process;

    res_TVALID <= regslice_both_res_V_data_V_U_vld_out;

    res_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, res_TREADY_int_regslice)
    begin
        if ((((res_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((res_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            res_TVALID_int_regslice <= ap_const_logic_1;
        else 
            res_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    select_ln54_fu_272_p3 <= 
        ap_const_lv16_1 when (out_data_last_fu_260_p2(0) = '1') else 
        add_ln54_fu_266_p2;
    select_ln60_fu_286_p3 <= 
        ap_const_lv16_0 when (out_data_last_1_fu_280_p2(0) = '1') else 
        select_ln54_fu_272_p3;
    zext_ln22_fu_228_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(write_idx),64));
    zext_ln32_fu_300_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tap_num_m1_read_reg_335),10));
end behav;
