// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module fir_hw_fir_hw_Pipeline_VITIS_LOOP_32_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        add_ln32,
        write_idx_load,
        coeff_hw_address0,
        coeff_hw_ce0,
        coeff_hw_q0,
        out_data_data_out,
        out_data_data_out_ap_vld,
        out_data_data_1_out,
        out_data_data_1_out_ap_vld,
        buffer_left_address0,
        buffer_left_ce0,
        buffer_left_q0,
        buffer_right_address0,
        buffer_right_ce0,
        buffer_right_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [9:0] add_ln32;
input  [8:0] write_idx_load;
output  [8:0] coeff_hw_address0;
output   coeff_hw_ce0;
input  [31:0] coeff_hw_q0;
output  [31:0] out_data_data_out;
output   out_data_data_out_ap_vld;
output  [31:0] out_data_data_1_out;
output   out_data_data_1_out_ap_vld;
output  [8:0] buffer_left_address0;
output   buffer_left_ce0;
input  [23:0] buffer_left_q0;
output  [8:0] buffer_right_address0;
output   buffer_right_ce0;
input  [23:0] buffer_right_q0;

reg ap_idle;
reg out_data_data_out_ap_vld;
reg out_data_data_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln32_fu_203_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln32_reg_408;
wire    ap_block_pp0_stage0_11001;
reg   [23:0] sample_r_reg_427;
wire    ap_block_pp0_stage1_11001;
wire  signed [78:0] sext_ln38_1_fu_257_p1;
reg  signed [78:0] sext_ln38_1_reg_432;
wire   [63:0] zext_ln36_fu_230_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln32_fu_215_p1;
reg   [31:0] out_data_data_1_fu_86;
wire    ap_loop_init;
reg   [31:0] out_data_data_fu_90;
reg   [47:0] acc_l_fu_94;
wire    ap_block_pp0_stage1;
reg   [47:0] acc_r_fu_98;
reg   [9:0] i_fu_102;
wire   [9:0] i_2_fu_209_p2;
reg   [9:0] ap_sig_allocacmp_i_1;
wire    ap_block_pp0_stage0_01001;
reg    buffer_left_ce0_local;
reg    buffer_right_ce0_local;
reg    coeff_hw_ce0_local;
reg  signed [46:0] grp_fu_171_p0;
wire  signed [78:0] sext_ln38_fu_252_p1;
wire  signed [78:0] sext_ln39_fu_316_p1;
reg  signed [31:0] grp_fu_171_p1;
wire   [8:0] trunc_ln35_fu_220_p1;
wire   [8:0] read_idx_fu_224_p2;
wire   [46:0] shl_ln_fu_244_p3;
wire   [78:0] shl_ln38_1_fu_262_p3;
wire   [78:0] grp_fu_171_p2;
wire   [78:0] add_ln38_fu_270_p2;
wire   [46:0] shl_ln1_fu_309_p3;
wire   [78:0] shl_ln39_1_fu_321_p3;
wire   [78:0] add_ln39_fu_329_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 out_data_data_1_fu_86 = 32'd0;
#0 out_data_data_fu_90 = 32'd0;
#0 acc_l_fu_94 = 48'd0;
#0 acc_r_fu_98 = 48'd0;
#0 i_fu_102 = 10'd0;
#0 ap_done_reg = 1'b0;
end

fir_hw_mul_47s_32s_79_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 47 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 79 ))
mul_47s_32s_79_1_1_U1(
    .din0(grp_fu_171_p0),
    .din1(grp_fu_171_p1),
    .dout(grp_fu_171_p2)
);

fir_hw_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        acc_l_fu_94 <= 48'd0;
    end else if (((icmp_ln32_reg_408 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        acc_l_fu_94 <= {{add_ln38_fu_270_p2[78:31]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            acc_r_fu_98 <= 48'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            acc_r_fu_98 <= {{add_ln39_fu_329_p2[78:31]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln32_fu_203_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_102 <= i_2_fu_209_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_102 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            out_data_data_1_fu_86 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            out_data_data_1_fu_86 <= {{add_ln39_fu_329_p2[77:46]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        out_data_data_fu_90 <= 32'd0;
    end else if (((icmp_ln32_reg_408 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        out_data_data_fu_90 <= {{add_ln38_fu_270_p2[77:46]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln32_reg_408 <= icmp_ln32_fu_203_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        sample_r_reg_427 <= buffer_right_q0;
        sext_ln38_1_reg_432 <= sext_ln38_1_fu_257_p1;
    end
end

always @ (*) begin
    if (((icmp_ln32_fu_203_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 10'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_102;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_left_ce0_local = 1'b1;
    end else begin
        buffer_left_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_right_ce0_local = 1'b1;
    end else begin
        buffer_right_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        coeff_hw_ce0_local = 1'b1;
    end else begin
        coeff_hw_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_171_p0 = sext_ln39_fu_316_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_171_p0 = sext_ln38_fu_252_p1;
    end else begin
        grp_fu_171_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_171_p1 = sext_ln38_1_reg_432;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_171_p1 = sext_ln38_1_fu_257_p1;
    end else begin
        grp_fu_171_p1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln32_fu_203_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_data_data_1_out_ap_vld = 1'b1;
    end else begin
        out_data_data_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln32_fu_203_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_data_data_out_ap_vld = 1'b1;
    end else begin
        out_data_data_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln38_fu_270_p2 = (shl_ln38_1_fu_262_p3 + grp_fu_171_p2);

assign add_ln39_fu_329_p2 = (shl_ln39_1_fu_321_p3 + grp_fu_171_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign buffer_left_address0 = zext_ln36_fu_230_p1;

assign buffer_left_ce0 = buffer_left_ce0_local;

assign buffer_right_address0 = zext_ln36_fu_230_p1;

assign buffer_right_ce0 = buffer_right_ce0_local;

assign coeff_hw_address0 = zext_ln32_fu_215_p1;

assign coeff_hw_ce0 = coeff_hw_ce0_local;

assign i_2_fu_209_p2 = (ap_sig_allocacmp_i_1 + 10'd1);

assign icmp_ln32_fu_203_p2 = ((ap_sig_allocacmp_i_1 == add_ln32) ? 1'b1 : 1'b0);

assign out_data_data_1_out = out_data_data_1_fu_86;

assign out_data_data_out = out_data_data_fu_90;

assign read_idx_fu_224_p2 = (write_idx_load - trunc_ln35_fu_220_p1);

assign sext_ln38_1_fu_257_p1 = $signed(coeff_hw_q0);

assign sext_ln38_fu_252_p1 = $signed(shl_ln_fu_244_p3);

assign sext_ln39_fu_316_p1 = $signed(shl_ln1_fu_309_p3);

assign shl_ln1_fu_309_p3 = {{sample_r_reg_427}, {23'd0}};

assign shl_ln38_1_fu_262_p3 = {{acc_l_fu_94}, {31'd0}};

assign shl_ln39_1_fu_321_p3 = {{acc_r_fu_98}, {31'd0}};

assign shl_ln_fu_244_p3 = {{buffer_left_q0}, {23'd0}};

assign trunc_ln35_fu_220_p1 = ap_sig_allocacmp_i_1[8:0];

assign zext_ln32_fu_215_p1 = ap_sig_allocacmp_i_1;

assign zext_ln36_fu_230_p1 = read_idx_fu_224_p2;

endmodule //fir_hw_fir_hw_Pipeline_VITIS_LOOP_32_1
